import { Component, ReactNode, useState, useEffect, useRef, useMemo, useCallback } from 'react';
import { StyleSheet, Text, View, Pressable, ScrollView, ActivityIndicator } from 'react-native';
import MapView, { Polyline, UrlTile, PROVIDER_DEFAULT, MapPressEvent, MapType, Region } from 'react-native-maps';
import * as Location from 'expo-location';
import * as Battery from 'expo-battery';
import * as TaskManager from 'expo-task-manager';
import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as DocumentPicker from 'expo-document-picker';
import * as store from './src/storage';
import { RoadNetwork, RoadSegment, parseChunkId, baseChunkId } from './src/roadMatcher';
import { DriveMatcher, Point, PieceIndex, isPatchy } from './src/coverage';
import { recheckDrives } from './src/recheck';
import { HEAT_STEPS, heatStep, stepColor, rankRoads, RoadRank } from './src/heat';
import { Coord, lineLengthMeters, distanceMeters, tileIdForPoint, neighbourTileIds, simplifyLine } from './src/geo';

// Every road tile is fetched live from the public repo over GitHub's raw
// file CDN. Tile ids must match scripts/tile-county.js (see src/geo.ts).
const TILES_BASE_URL = 'https://raw.githubusercontent.com/0204Killian/tarmacked/main/tiles/';
const LOCATION_TASK_NAME = 'tarmacked-background-location';

// Edit mode only draws roads once zoomed in this far (a few km across).
const EDIT_MAX_LAT_DELTA = 0.06;
// A pause longer than this inside one old recording = two separate drives.
const DRIVE_SPLIT_GAP_MS = 15 * 60 * 1000;
const NOTE_MS = 7000;
// Bumped whenever the road-matching rules change, so saved drives are
// replayed once under the new rules. 2 = v0.14.1 (route-aware matching),
// 3 = v0.14.2 (roads marked since trails were saved must be re-earned).
const MATCHER_REV = 3;
const LOG_LINES = 60;

// Real road totals for every county and the whole Republic, generated by
// scripts/tile-county.js alongside the tiles. Cached for offline use.
type CountyStats = { counties: string[]; totalMeters: number[]; nationalMeters: number };
type Panel = null | 'stats' | 'drives' | 'dev';
type Chain = { coords: Coord[]; minLat: number; maxLat: number; minLon: number; maxLon: number };

const shortCounty = (name: string) => name.replace(/^County /, '');
// 'osm' = OpenStreetMap tiles drawn over a plain Apple map (the default).
type MapChoice = 'osm' | MapType;
const MAP_TYPES: MapChoice[] = ['osm', 'standard', 'satellite', 'hybrid'];
const MAP_LABELS: Record<MapChoice, string> = { osm: 'OSM', standard: 'Apple', satellite: 'Satellite', hybrid: 'Hybrid' } as Record<MapChoice, string>;
const OSM_TILE_URL = 'https://tile.openstreetmap.org/{z}/{x}/{y}.png';

// GPS accuracy modes. Savings come from logging less often and letting
// the phone batch updates; accuracy stays high in every mode so points
// aren't thrown away by the wild-GPS filter.
type AccuracyMode = 'high' | 'balanced' | 'saver' | 'auto';
const ACCURACY_MODES: { key: AccuracyMode; label: string; info: string }[] = [
  { key: 'high', label: 'High', info: 'Recommended. A point every ~10 m. Most accurate, most battery.' },
  { key: 'balanced', label: 'Balanced', info: 'A point every ~20 m, delivered in batches. Less battery.' },
  { key: 'saver', label: 'Saver', info: 'A point every ~35 m, big batches. Least battery; short roads may be missed.' },
  { key: 'auto', label: 'Auto', info: 'High while charging, Balanced on battery.' },
];
function locationOptions(mode: 'high' | 'balanced' | 'saver') {
  if (mode === 'high') return { accuracy: Location.Accuracy.BestForNavigation, timeInterval: 2000, distanceInterval: 10 };
  if (mode === 'balanced')
    return { accuracy: Location.Accuracy.High, timeInterval: 3000, distanceInterval: 20, deferredUpdatesInterval: 15000, deferredUpdatesDistance: 200 };
  return { accuracy: Location.Accuracy.High, timeInterval: 5000, distanceInterval: 35, deferredUpdatesInterval: 60000, deferredUpdatesDistance: 800 };
}
const isCharging = (s: Battery.BatteryState) => s === Battery.BatteryState.CHARGING || s === Battery.BatteryState.FULL;
type StatsTab = 'overview' | 'counties' | 'roads' | 'data';
const STATS_TABS: { key: StatsTab; label: string }[] = [
  { key: 'overview', label: 'Overview' },
  { key: 'counties', label: 'Counties' },
  { key: 'roads', label: 'Roads' },
  { key: 'data', label: 'Your data' },
];
const FALLBACK_REGION = { latitude: 53.1, longitude: -7.7, latitudeDelta: 4, longitudeDelta: 4 };
const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

const pad2 = (n: number) => String(n).padStart(2, '0');
function formatWhen(t: number) {
  const d = new Date(t);
  return `${DAYS[d.getDay()]} ${d.getDate()} ${MONTHS[d.getMonth()]} · ${pad2(d.getHours())}:${pad2(d.getMinutes())}`;
}
function formatDuration(ms: number) {
  const min = Math.max(0, Math.round(ms / 60000));
  return min < 60 ? `${min} min` : `${Math.floor(min / 60)}h ${pad2(min % 60)}m`;
}
const km = (m: number, dp = 1) => (m / 1000).toFixed(dp);
const toLatLng = (c: Coord[]) => c.map(([latitude, longitude]) => ({ latitude, longitude }));

// Joins driven chunks of the same road into continuous lines, so the map
// draws a few long lines instead of thousands of 100m pieces.
function buildChains(ids: Iterable<string>, shapeOf: (id: string) => Coord[] | undefined): Chain[] {
  const byWay = new Map<string, { idx: number; coords: Coord[] }[]>();
  const loose: Coord[][] = [];
  for (const id of ids) {
    const coords = shapeOf(id);
    if (!coords || coords.length < 2) continue;
    const p = parseChunkId(id);
    if (!p) {
      loose.push(coords);
      continue;
    }
    const list = byWay.get(p.way);
    if (list) list.push({ idx: p.idx, coords });
    else byWay.set(p.way, [{ idx: p.idx, coords }]);
  }
  const lines: Coord[][] = [...loose];
  byWay.forEach((parts) => {
    parts.sort((a, b) => a.idx - b.idx);
    let cur = parts[0].coords.slice();
    for (let i = 1; i < parts.length; i++) {
      const prevEnd = cur[cur.length - 1];
      const next = parts[i].coords;
      if (parts[i].idx === parts[i - 1].idx + 1 && prevEnd[0] === next[0][0] && prevEnd[1] === next[0][1]) {
        cur.push(...next.slice(1));
      } else {
        lines.push(cur);
        cur = next.slice();
      }
    }
    lines.push(cur);
  });
  return stitchLines(lines).map((coords) => {
    let minLat = Infinity, maxLat = -Infinity, minLon = Infinity, maxLon = -Infinity;
    for (const [la, lo] of coords) {
      if (la < minLat) minLat = la;
      if (la > maxLat) maxLat = la;
      if (lo < minLon) minLon = lo;
      if (lo > maxLon) maxLon = lo;
    }
    return { coords, minLat, maxLat, minLon, maxLon };
  });
}

// Joins lines end to end wherever exactly two of them meet (e.g. where one
// road continues as another, or around a roundabout), so the map draws one
// smooth line instead of separate pieces with visible joins.
function stitchLines(input: Coord[][]): Coord[][] {
  let lines = input.filter((l) => l.length >= 2);
  const key = (c: Coord) => `${c[0]},${c[1]}`;
  for (let pass = 0; pass < 50; pass++) {
    const ends = new Map<string, { i: number; atStart: boolean }[]>();
    lines.forEach((l, i) => {
      for (const [c, atStart] of [[l[0], true], [l[l.length - 1], false]] as [Coord, boolean][]) {
        const k = key(c);
        const list = ends.get(k);
        if (list) list.push({ i, atStart });
        else ends.set(k, [{ i, atStart }]);
      }
    });
    const used = new Set<number>();
    const out: Coord[][] = [];
    ends.forEach((list) => {
      if (list.length !== 2) return;
      const [a, b] = list;
      if (a.i === b.i || used.has(a.i) || used.has(b.i)) return;
      used.add(a.i);
      used.add(b.i);
      // Orient so the first line ends at the shared point and the second starts there.
      const first = a.atStart ? lines[a.i].slice().reverse() : lines[a.i];
      const second = b.atStart ? lines[b.i] : lines[b.i].slice().reverse();
      out.push([...first, ...second.slice(1)]);
    });
    if (used.size === 0) return lines;
    lines.forEach((l, i) => {
      if (!used.has(i)) out.push(l);
    });
    lines = out;
  }
  return lines;
}

// --- Background location: points land here and are picked up every 2s ---
let recordedPoints: Point[] = [];

TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }) => {
  if (error) {
    console.error(error);
    return;
  }
  if (data) {
    const { locations } = data as { locations: Location.LocationObject[] };
    for (const loc of locations) {
      recordedPoints.push({
        latitude: loc.coords.latitude,
        longitude: loc.coords.longitude,
        timestamp: loc.timestamp,
        accuracy: loc.coords.accuracy ?? null,
      });
    }
  }
});

function withTimeout<T>(promise: Promise<T>, ms: number, label: string): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>((_, reject) => setTimeout(() => reject(new Error(`${label} timed out after ${ms / 1000}s`)), ms)),
  ]);
}

// If anything goes wrong while drawing the screen, show the error instead
// of a blank screen, so it can be reported.
class CrashScreen extends Component<{ children: ReactNode }, { error: Error | null }> {
  state = { error: null as Error | null };
  static getDerivedStateFromError(error: Error) {
    return { error };
  }
  render() {
    const { error } = this.state;
    if (!error) return this.props.children;
    return (
      <View style={styles.onboardContainer}>
        <Text style={styles.onboardTitle}>Something went wrong</Text>
        <Text style={styles.onboardText}>Screenshot this and send it on:</Text>
        <ScrollView style={styles.countyList}>
          <Text style={styles.logText}>{`${error.message}\n\n${error.stack ?? ''}`}</Text>
        </ScrollView>
      </View>
    );
  }
}

export default function Root() {
  return (
    <CrashScreen>
      <App />
    </CrashScreen>
  );
}

function App() {
  // null = still loading; false = needs onboarding; true = ready
  const [onboarded, setOnboarded] = useState<boolean | null>(null);
  const [onboardingCounties, setOnboardingCounties] = useState<string[] | null>(null);
  const [onboardingError, setOnboardingError] = useState('');
  const [downloadingCounty, setDownloadingCounty] = useState<string | null>(null);
  const [downloadProgress, setDownloadProgress] = useState({ done: 0, total: 0 });
  const [homeCounty, setHomeCounty] = useState<string | null>(null);

  const [tracking, setTracking] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [editAction, setEditAction] = useState<'exclude' | 'undrive'>('exclude');
  const [following, setFollowing] = useState(true);
  const [panel, setPanel] = useState<Panel>(null);
  const [mapTypeIndex, setMapTypeIndex] = useState(0);
  const [region, setRegion] = useState(FALLBACK_REGION);
  const [visibleRegion, setVisibleRegion] = useState<Region>(FALLBACK_REGION);
  const mapRef = useRef<MapView | null>(null);

  // Driven / excluded roads. The refs are the source of truth (read inside
  // timers and async work); the state copies make the screen update.
  const drivenRef = useRef<Set<string>>(new Set());
  const excludedRef = useRef<Set<string>>(new Set());
  const [drivenIds, setDrivenIds] = useState<Set<string>>(new Set());
  const [excludedIds, setExcludedIds] = useState<Set<string>>(new Set());
  // Stored with each driven road so it draws and counts even when the road
  // data for that area isn't downloaded.
  const drivenShapesRef = useRef<Map<string, Coord[]>>(new Map());
  const drivenCountyRef = useRef<Map<string, number>>(new Map());
  const lengthRef = useRef<Map<string, number>>(new Map());
  const excludedInfoRef = useRef<Map<string, { c: number | null; l: number | null }>>(new Map());
  const unmarkedRef = useRef<Map<string, number>>(new Map());
  // Partly-driven road pieces: covered stretches that add up across drives.
  const partialsRef = useRef<Map<string, [number, number][]>>(new Map());

  // Downloaded road data.
  const netRef = useRef(new RoadNetwork());
  const knownTilesRef = useRef<Set<string>>(new Set());
  const [netRev, setNetRev] = useState(0);

  const [countyStats, setCountyStats] = useState<CountyStats | null>(null);
  const [currentCounty, setCurrentCounty] = useState<number | null>(null);

  // The drive in progress.
  const matcherRef = useRef<DriveMatcher | null>(null);
  const currentDriveIdRef = useRef<number | null>(null);
  const driveStartRef = useRef(0);
  const driveDistanceRef = useRef(0);
  const driveNewMRef = useRef(0);
  const lastLivePointRef = useRef<Point | null>(null);
  const processedIndexRef = useRef(0);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const foregroundSub = useRef<Location.LocationSubscription | null>(null);
  const [liveIds, setLiveIds] = useState<string[]>([]);
  const [liveTrail, setLiveTrail] = useState<Point[]>([]);
  const [accuracyMode, setAccuracyMode] = useState<AccuracyMode>('high');
  const activeModeRef = useRef<'high' | 'balanced' | 'saver'>('high');
  const batterySub = useRef<{ remove(): void } | null>(null);

  // Heatmap: how many drives covered each chunk.
  const [roadCounts, setRoadCounts] = useState<Map<string, number>>(new Map());
  const [heatOn, setHeatOn] = useState(false);
  // A most-driven stretch picked from Stats → Roads, highlighted on the map.
  const [highlight, setHighlight] = useState<{ name: string; count: number; chunks: string[] } | null>(null);
  const [statsTab, setStatsTab] = useState<StatsTab>('overview');

  // Drives list / drive shown on the map.
  const [drives, setDrives] = useState<store.DriveSummary[] | null>(null);
  const [selectedDrive, setSelectedDrive] = useState<{ id: number; points: Point[]; roads: string[] } | null>(null);
  const [deleteConfirmId, setDeleteConfirmId] = useState<number | null>(null);

  // Dev / housekeeping.
  const [unmatchedCount, setUnmatchedCount] = useState(0);
  const [rawStats, setRawStats] = useState({ drives: 0, points: 0 });
  const [rawSessions, setRawSessions] = useState<Point[][] | null>(null);
  const [recheckProgress, setRecheckProgress] = useState<number | null>(null);
  const [removedCount, setRemovedCount] = useState(0);
  const [simulateTaps, setSimulateTaps] = useState(false);
  const [confirming, setConfirming] = useState<null | 'reset' | 'uninstall'>(null);
  const [backupBusy, setBackupBusy] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [note, setNoteText] = useState('');
  const noteTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [log, setLog] = useState<string[]>([]);

  // Map drawing.
  const [dataLoaded, setDataLoaded] = useState(false);
  const [bootStep, setBootStep] = useState('Starting…');

  const setNote = useCallback((text: string) => {
    setNoteText(text);
    if (noteTimer.current) clearTimeout(noteTimer.current);
    if (text) noteTimer.current = setTimeout(() => setNoteText(''), NOTE_MS);
  }, []);
  const addLog = useCallback((line: string) => {
    const d = new Date();
    setLog((prev) => [...prev.slice(-(LOG_LINES - 1)), `${pad2(d.getHours())}:${pad2(d.getMinutes())} ${line}`]);
  }, []);

  // ---------- Driven-road bookkeeping ----------

  const rememberDriven = (id: string, shape: Coord[] | null, county: number | null) => {
    if (shape) {
      drivenShapesRef.current.set(id, shape);
      lengthRef.current.set(id, lineLengthMeters(shape));
    }
    if (county !== null) drivenCountyRef.current.set(id, county);
  };

  const forgetDriven = (id: string) => {
    drivenShapesRef.current.delete(id);
    drivenCountyRef.current.delete(id);
    lengthRef.current.delete(id);
  };

  // Marks road pieces as driven. A piece already covered by a driven one
  // adds nothing; smaller pieces a new one covers (e.g. a start/stop
  // stretch, later driven in full) are replaced by it.
  // Returns the new pieces and the metres of road they add.
  const markDriven = (ids: string[]): { fresh: string[]; newM: number } => {
    const net = netRef.current;
    const bases = new Set(ids.map(baseChunkId));
    const index = new PieceIndex(Array.from(drivenRef.current).filter((d) => bases.has(baseChunkId(d))));
    const fresh: string[] = [];
    const replaced: string[] = [];
    let newM = 0;
    for (const id of ids) {
      if (excludedRef.current.has(baseChunkId(id)) || index.coveredBy(id)) continue;
      for (const old of index.within(id)) {
        index.delete(old);
        replaced.push(old);
        newM -= lengthRef.current.get(old) ?? net.length(old);
      }
      index.add(id);
      fresh.push(id);
    }
    if (fresh.length === 0) return { fresh, newM: 0 };
    for (const old of replaced) {
      drivenRef.current.delete(old);
      forgetDriven(old);
    }
    const stillFresh = fresh.filter((id) => !replaced.includes(id));
    const rows = stillFresh.map((id) => {
      const shape = drivenShapesRef.current.get(id) ?? net.shapeOf(id);
      const county = drivenCountyRef.current.get(id) ?? net.countyOf(id);
      rememberDriven(id, shape, county);
      drivenRef.current.add(id);
      newM += lengthRef.current.get(id) ?? net.length(id);
      return { id, shape, county };
    });
    setDrivenIds(new Set(drivenRef.current));
    store
      .applyRecheck(rows, replaced, false)
      .catch((e) => setNote(`Couldn't save driven roads: ${(e as Error).message}`));
    return { fresh: stillFresh, newM: Math.max(0, newM) };
  };

  // When road data arrives, fill in shape/county/length for driven or
  // excluded roads we didn't know them for (e.g. older history).
  const backfillFromSegments = (segs: RoadSegment[]) => {
    const drivenFill: { id: string; shape: Coord[]; county: number | null }[] = [];
    const excludedFill: { id: string; county: number | null; lengthM: number }[] = [];
    for (const seg of segs) {
      if (drivenRef.current.has(seg.id)) {
        const needShape = !drivenShapesRef.current.has(seg.id);
        const needCounty = seg.c !== undefined && !drivenCountyRef.current.has(seg.id);
        if (needShape || needCounty) {
          const shape = drivenShapesRef.current.get(seg.id) ?? seg.coords;
          rememberDriven(seg.id, shape, seg.c ?? null);
          drivenFill.push({ id: seg.id, shape, county: seg.c ?? null });
        }
      }
      const ex = excludedInfoRef.current.get(seg.id);
      if (ex && (ex.c === null || ex.l === null)) {
        const next = { c: ex.c ?? seg.c ?? null, l: ex.l ?? lineLengthMeters(seg.coords) };
        excludedInfoRef.current.set(seg.id, next);
        excludedFill.push({ id: seg.id, county: next.c, lengthM: next.l });
      }
    }
    if (drivenFill.length > 0) store.addDriven(drivenFill).catch(() => undefined);
    if (excludedFill.length > 0) store.fillExcludedInfo(excludedFill).catch(() => undefined);
    return drivenFill.length;
  };

  const addRoadData = (segs: RoadSegment[]) => {
    if (segs.length === 0) return;
    netRef.current.add(segs);
    const filled = backfillFromSegments(segs);
    setNetRev((r) => r + 1);
    if (filled > 0) setDrivenIds(new Set(drivenRef.current)); // stats may change
  };

  // ---------- Road data tiles ----------

  // 'ok' = downloaded (or nothing there), 'fail' = network problem.
  const fetchTile = async (tileId: string): Promise<'ok' | 'fail'> => {
    if (knownTilesRef.current.has(tileId)) return 'ok';
    knownTilesRef.current.add(tileId); // mark in-flight so bursts don't duplicate
    try {
      const res = await fetch(`${TILES_BASE_URL}${tileId}.json`);
      if (!res.ok) return 'ok'; // not tiled (sea, outside Ireland)
      const data = await res.json();
      const segs: RoadSegment[] = data.segments || [];
      if (segs.length > 0) {
        addRoadData(segs);
        addLog(`road data: ${tileId} (${segs.length})`);
        store.putTiles([{ tileId, segments: segs }], false).catch(() => undefined);
      }
      return 'ok';
    } catch {
      knownTilesRef.current.delete(tileId); // retry later
      return 'fail';
    }
  };

  // Downloads any of these tiles we don't have. Returns how many failed.
  const ensureTiles = async (tileIds: Iterable<string>, onProgress?: (f: number) => void) => {
    const missing = Array.from(new Set(tileIds)).filter((t) => !knownTilesRef.current.has(t));
    let failed = 0;
    for (let i = 0; i < missing.length; i += 8) {
      const results = await Promise.all(missing.slice(i, i + 8).map(fetchTile));
      failed += results.filter((r) => r === 'fail').length;
      onProgress?.(Math.min(1, (i + 8) / missing.length));
    }
    return failed;
  };

  const downloadHomeCounty = async (county: string) => {
    setDownloadingCounty(county);
    setOnboardingError('');
    try {
      const indexRes = await fetch(`${TILES_BASE_URL}county-index.json`);
      const index = await indexRes.json();
      const tileIds: string[] = index[county] || [];
      setDownloadProgress({ done: 0, total: tileIds.length });
      const entries: store.TileEntry[] = [];
      for (let i = 0; i < tileIds.length; i += 8) {
        const results = await Promise.all(
          tileIds.slice(i, i + 8).map(async (tileId) => {
            try {
              const res = await fetch(`${TILES_BASE_URL}${tileId}.json`);
              if (!res.ok) return { tileId, segments: [] as RoadSegment[] };
              const data = await res.json();
              return { tileId, segments: (data.segments || []) as RoadSegment[] };
            } catch {
              return { tileId, segments: [] as RoadSegment[] };
            }
          })
        );
        for (const r of results) {
          if (r.segments.length > 0) entries.push(r);
          knownTilesRef.current.add(r.tileId);
        }
        setDownloadProgress({ done: Math.min(i + 8, tileIds.length), total: tileIds.length });
      }
      addRoadData(entries.flatMap((e) => e.segments));
      await store.putTiles(entries, true); // home county is never auto-cleared
      await store.setMeta('home_county', county);
      await store.setMeta('onboarded', 'true');
      setHomeCounty(county);
      setOnboarded(true);
      return true;
    } catch (e) {
      setOnboardingError(`Download failed: ${(e as Error).message}. Check your connection and try again.`);
      return false;
    } finally {
      setDownloadingCounty(null);
    }
  };

  const skipOnboarding = async () => {
    await store.setMeta('onboarded', 'true');
    setOnboarded(true);
  };

  // ---------- Loading ----------

  useEffect(() => {
    (async () => {
      try {
        setBootStep('Opening your data…');
        const migrated = await store.migrateIfNeeded();
        if (migrated) setNote(migrated);
      } catch (e) {
        setNote(`Couldn't move your data to the new storage yet (${(e as Error).message}). Nothing was deleted — it retries next launch.`);
      }
      try {
        setBootStep('Clearing old road data…');
        await store.evictStaleTiles();
        setBootStep('Loading your roads…');
        const data = await store.loadAll();
        setBootStep('Setting up the map…');
        for (const d of data.driven) {
          drivenRef.current.add(d.id);
          rememberDriven(d.id, d.shape, d.county);
        }
        for (const e of data.excluded) {
          excludedRef.current.add(e.id);
          excludedInfoRef.current.set(e.id, { c: e.county, l: e.lengthM });
        }
        unmarkedRef.current = await store.loadUnmarked();
        partialsRef.current = await store.loadPartials();
        setRoadCounts(await store.loadRoadCounts());
        const savedMode = (await store.getMeta('accuracy_mode')) as AccuracyMode | null;
        if (savedMode && ACCURACY_MODES.some((m) => m.key === savedMode)) setAccuracyMode(savedMode);
        const savedMap = await store.getMeta('map_type');
        if (savedMap && MAP_TYPES.includes(savedMap as MapChoice)) setMapTypeIndex(MAP_TYPES.indexOf(savedMap as MapChoice));
        const segs = data.tiles.flatMap((t) => t.segments);
        data.tiles.forEach((t) => knownTilesRef.current.add(t.tileId));
        addRoadData(segs);
        setDrivenIds(new Set(drivenRef.current));
        setExcludedIds(new Set(excludedRef.current));
        setUnmatchedCount(data.unmatched.length);
        setRawStats({ drives: data.driveCount, points: data.pointCount });
        setRemovedCount(await store.countRemoved());
        if (data.homeCounty) setHomeCounty(data.homeCounty);
        setOnboarded(data.onboarded);
        setDataLoaded(true);
      } catch (e) {
        setBootStep(`Couldn't load saved data: ${(e as Error).message}`);
        setNote(`Couldn't load saved data: ${(e as Error).message}`);
        setOnboarded(false);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // County totals: cached copy straight away, then a fresh one from GitHub.
  useEffect(() => {
    (async () => {
      try {
        const cached = await store.getMeta('county_stats');
        if (cached) setCountyStats(JSON.parse(cached));
      } catch {
        // no cached copy yet
      }
      try {
        const res = await fetch(`${TILES_BASE_URL}county-stats.json`);
        if (!res.ok) return;
        const fresh = await res.json();
        if (!Array.isArray(fresh.counties) || !Array.isArray(fresh.totalMeters)) return;
        setCountyStats(fresh);
        await store.setMeta('county_stats', JSON.stringify(fresh));
      } catch {
        // offline — the cached copy (if any) stays in use
      }
    })();
  }, []);

  useEffect(() => {
    if (onboarded !== false || onboardingCounties !== null) return;
    (async () => {
      try {
        const res = await fetch(`${TILES_BASE_URL}county-index.json`);
        if (!res.ok) throw new Error(`index responded ${res.status}`);
        const index = await res.json();
        setOnboardingCounties(Object.keys(index).sort());
      } catch (e) {
        setOnboardingError(`Couldn't reach GitHub to list counties (${(e as Error).message}). Check your connection and try again.`);
      }
    })();
  }, [onboarded, onboardingCounties]);

  // Location permissions and a first fix to centre the map.
  useEffect(() => {
    if (onboarded !== true) return;
    (async () => {
      try {
        const fg = await withTimeout(Location.requestForegroundPermissionsAsync(), 8000, 'foreground permission');
        addLog(`location permission: ${fg.status}`);
      } catch (e) {
        addLog(`location permission failed: ${(e as Error).message}`);
      }
      try {
        const bg = await withTimeout(Location.requestBackgroundPermissionsAsync(), 8000, 'background permission');
        addLog(`background permission: ${bg.status}`);
      } catch (e) {
        addLog(`background permission failed: ${(e as Error).message}`);
      }
      try {
        const current = await withTimeout(Location.getCurrentPositionAsync({}), 8000, 'get current position');
        const here = { latitude: current.coords.latitude, longitude: current.coords.longitude, latitudeDelta: 0.05, longitudeDelta: 0.05 };
        setRegion(here);
        setVisibleRegion(here);
        mapRef.current?.animateToRegion(here, 300);
      } catch (e) {
        addLog(`no position yet: ${(e as Error).message}`);
      }
    })();
  }, [onboarded, addLog]);

  // ---------- Re-checking drives ----------

  const recheckRunning = useRef(false);

  /**
   * Replays every saved drive through the matching rules and updates which
   * roads count as driven (adding and removing). Downloads road data for
   * everywhere you've driven first; if that isn't possible (no signal) it
   * does nothing and tries again later. Removed roads can be put back.
   */
  const runRecheck = async (reason: 'upgrade' | 'manual' | 'deleted'): Promise<boolean> => {
    if (recheckRunning.current) return false;
    recheckRunning.current = true;
    setRecheckProgress(0);
    try {
      const allDrives = await store.loadDrives();
      // Trails of deleted drives still waiting for their roads to be removed.
      let forgotten: Point[][] = [];
      try {
        forgotten = JSON.parse((await store.getMeta('forgotten_trails')) || '[]');
      } catch {
        forgotten = [];
      }
      // Left-out drives earn nothing; their trails are only used to find
      // the roads to re-check (like a deleted drive's).
      const counted = allDrives.filter((d) => !d.leftOut);
      const leftOutTrails = allDrives.filter((d) => d.leftOut).map((d) => d.points);
      const tiles = new Set<string>();
      const visited = new Set<string>();
      for (const points of [...allDrives.map((d) => d.points), ...forgotten]) {
        for (const p of points) {
          const own = tileIdForPoint(p.latitude, p.longitude);
          if (visited.has(own)) continue;
          visited.add(own);
          neighbourTileIds(p.latitude, p.longitude).forEach((t) => tiles.add(t));
        }
      }
      // Also the road data for driven roads we have no county for yet.
      drivenRef.current.forEach((id) => {
        if (drivenCountyRef.current.has(id)) return;
        const shape = drivenShapesRef.current.get(id);
        if (shape) tiles.add(tileIdForPoint(shape[0][0], shape[0][1]));
      });
      const failed = await ensureTiles(tiles, (f) => setRecheckProgress(f * 0.3));
      if (failed > 0) {
        await store.setMeta('recheck_pending', '1');
        setNote(`Couldn't download road data for ${failed} area(s) — I'll re-check your drives next time you have signal.`);
        return false;
      }
      const current = new Map<string, Coord[] | null>();
      drivenRef.current.forEach((id) => current.set(id, drivenShapesRef.current.get(id) ?? null));
      // GPS trails have been saved since the earliest drive (or trail of a
      // deleted one); roads marked before that, or carried over from the
      // old storage, are the only ones kept without a drive to back them.
      const trailStarts = [...allDrives.map((d) => d.startedAt), ...forgotten.filter((t) => t.length).map((t) => t[0].timestamp)];
      const migratedAt = Number((await store.getMeta('migrated_from_asyncstorage')) || 0);
      const trailsSince = Math.max(trailStarts.length ? Math.min(...trailStarts) : Infinity, migratedAt + 1);
      const result = await recheckDrives(
        netRef.current,
        counted,
        current,
        excludedRef.current,
        unmarkedRef.current,
        (f) => setRecheckProgress(0.3 + f * 0.7),
        [...forgotten, ...leftOutTrails],
        { firstAt: await store.loadDrivenFirstAt(), trailsSince, pinned: await store.loadPinned() }
      );
      const net = netRef.current;
      const addRows = result.add.map((id) => ({ id, shape: net.shapeOf(id), county: net.countyOf(id) }));
      await store.applyRecheck(addRows, result.remove, reason !== 'deleted');
      await store.setMeta('forgotten_trails', '[]');
      await store.setDriveStats(result.stats);
      await store.replaceUnmatched(result.unmatched);
      await store.replacePartials(result.partials);
      await store.replaceAllDriveRoads(result.driveRoads);
      setRoadCounts(await store.loadRoadCounts());
      partialsRef.current = result.partials;
      await store.setMeta('recheck_pending', '');
      for (const r of addRows) {
        drivenRef.current.add(r.id);
        rememberDriven(r.id, r.shape, r.county);
      }
      for (const id of result.remove) {
        drivenRef.current.delete(id);
        forgetDriven(id);
      }
      setDrivenIds(new Set(drivenRef.current));
      setUnmatchedCount(result.unmatched.length);
      setRemovedCount(await store.countRemoved());
      setRawStats({ drives: allDrives.length, points: allDrives.reduce((n, d) => n + d.points.length, 0) });
      if (drives !== null) setDrives(await store.listDrives());
      const changed = result.add.length + result.remove.length;
      if (reason !== 'deleted' || changed > 0) {
        setNote(
          `Re-checked ${allDrives.length} drive(s): ${result.add.length} road pieces added, ${result.remove.length} removed.` +
            (result.remove.length > 0 ? ' Removed ones can be put back from Dev.' : '')
        );
      }
      addLog(`re-check (${reason}): +${result.add.length} −${result.remove.length}`);
      return true;
    } catch (e) {
      setNote(`Re-check failed: ${(e as Error).message}. Nothing was changed.`);
      return false;
    } finally {
      recheckRunning.current = false;
      setRecheckProgress(null);
    }
  };

  // First launch of v0.13: split old recordings into drives and re-check
  // everything with the new rule. Also retries a re-check that couldn't run.
  useEffect(() => {
    if (!dataLoaded || onboarded !== true) return;
    (async () => {
      const upgraded = await store.getMeta('v013_upgrade');
      const upgraded14 = await store.getMeta('v014_upgrade');
      const pending = await store.getMeta('recheck_pending');
      if (!upgraded) {
        const { split, dropped } = await store.splitDrivesOnGaps(DRIVE_SPLIT_GAP_MS);
        addLog(`drives tidied: ${split} split, ${dropped} empty removed`);
        await store.setMeta('v013_split', '1');
        if (await runRecheck('upgrade')) {
          await store.setMeta('v013_upgrade', String(Date.now()));
          await store.setMeta('v014_upgrade', String(Date.now()));
        }
      } else if (!upgraded14) {
        // v0.14: start/stop credit, wild-GPS filter and heatmap counts
        // are worked out for every saved drive.
        if (await runRecheck('upgrade')) {
          await store.setMeta('v014_upgrade', String(Date.now()));
          await store.setMeta('matcher_rev', String(MATCHER_REV));
        }
      } else if (Number((await store.getMeta('matcher_rev')) || '1') < MATCHER_REV) {
        // The road matcher changed (v0.14.1: slip roads, roundabouts):
        // replay every saved drive once so the whole map follows the new rules.
        if (await runRecheck('upgrade')) await store.setMeta('matcher_rev', String(MATCHER_REV));
      } else if (pending === '1') {
        await runRecheck('manual');
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dataLoaded, onboarded]);

  // ---------- Tracking ----------

  const processPoints = (newPoints: Point[]) => {
    if (newPoints.length === 0) return;
    // Fetch road data around you before you need it.
    const wanted = new Set<string>();
    for (const p of newPoints) neighbourTileIds(p.latitude, p.longitude).forEach((t) => wanted.add(t));
    wanted.forEach((t) => {
      if (!knownTilesRef.current.has(t)) fetchTile(t);
    });

    const matcher = matcherRef.current;
    // Distance only counts points that pass the wild-GPS filter.
    let good = newPoints;
    if (matcher) {
      const result = matcher.feed(newPoints);
      good = result.accepted;
      const { fresh, newM } = markDriven(result.completed);
      if (fresh.length > 0) {
        driveNewMRef.current += newM;
        setLiveIds((prev) => [...prev, ...fresh]);
      }
      if (result.unmatched.length > 0) {
        setUnmatchedCount((n) => n + result.unmatched.length);
        store.addUnmatched(result.unmatched).catch(() => undefined);
      }
      savePartialsFrom(matcher);
      const last = matcher.lastChunkId ? netRef.current.segs.get(matcher.lastChunkId) : undefined;
      if (last?.c !== undefined) setCurrentCounty(last.c);
    }

    for (const p of good) {
      const prev = lastLivePointRef.current;
      if (prev && p.timestamp - prev.timestamp <= 60_000) driveDistanceRef.current += distanceMeters(prev, p);
      lastLivePointRef.current = p;
    }
    const driveId = currentDriveIdRef.current;
    if (driveId !== null) {
      store.addPoints(driveId, newPoints).catch((e) => setNote(`Couldn't save GPS points: ${(e as Error).message}`));
    }
    setRawStats((prev) => ({ ...prev, points: prev.points + newPoints.length }));
    setLiveTrail((prev) => [...prev, ...newPoints]);
    store.touchTiles(Array.from(new Set(newPoints.map((p) => tileIdForPoint(p.latitude, p.longitude))))).catch(() => undefined);
  };

  // Saves the partly-driven stretches this drive changed.
  const savePartialsFrom = (matcher: DriveMatcher) => {
    if (matcher.touched.size === 0) return;
    const entries: [string, [number, number][] | null][] = Array.from(matcher.touched).map((id) => [
      id,
      partialsRef.current.get(id) ?? null,
    ]);
    matcher.touched.clear();
    store.savePartials(entries).catch(() => undefined);
  };

  const processRef = useRef(processPoints);
  processRef.current = processPoints;

  useEffect(() => {
    if (!tracking) return;
    pollRef.current = setInterval(() => {
      const newPoints = recordedPoints.slice(processedIndexRef.current);
      processedIndexRef.current = recordedPoints.length;
      processRef.current(newPoints);
    }, 2000);
    return () => {
      if (pollRef.current) clearInterval(pollRef.current);
    };
  }, [tracking]);

  const start = async () => {
    recordedPoints = [];
    processedIndexRef.current = 0;
    matcherRef.current = new DriveMatcher(netRef.current, excludedRef.current, partialsRef.current);
    driveStartRef.current = Date.now();
    driveDistanceRef.current = 0;
    driveNewMRef.current = 0;
    lastLivePointRef.current = null;
    setLiveIds([]);
    setLiveTrail([]);
    setSelectedDrive(null);
    setHighlight(null);
    setPanel(null);
    setFollowing(true);
    try {
      currentDriveIdRef.current = await store.startDrive(driveStartRef.current);
      setRawStats((prev) => ({ ...prev, drives: prev.drives + 1 }));
    } catch (e) {
      currentDriveIdRef.current = null;
      setNote(`Couldn't start saving this drive (${(e as Error).message}) — roads will still be matched.`);
    }
    let mode: 'high' | 'balanced' | 'saver' = accuracyMode === 'auto' ? 'balanced' : accuracyMode;
    if (accuracyMode === 'auto') {
      try {
        mode = isCharging(await Battery.getBatteryStateAsync()) ? 'high' : 'balanced';
        batterySub.current = Battery.addBatteryStateListener(({ batteryState }) => {
          const next = isCharging(batteryState) ? 'high' : 'balanced';
          if (next !== activeModeRef.current) startUpdates(next).catch(() => undefined);
        });
      } catch (e) {
        addLog(`battery state unavailable: ${(e as Error).message}`);
      }
    }
    try {
      await withTimeout(startUpdates(mode), 8000, 'start background tracking');
    } catch (e) {
      addLog(`background tracking unavailable: ${(e as Error).message}`);
      try {
        foregroundSub.current = await Location.watchPositionAsync(locationOptions(mode), (loc) => {
          recordedPoints.push({
            latitude: loc.coords.latitude,
            longitude: loc.coords.longitude,
            timestamp: loc.timestamp,
            accuracy: loc.coords.accuracy ?? null,
          });
        });
        setNote('Tracking only while the app is open (background location unavailable).');
      } catch {
        setNote('No GPS available.');
      }
    }
    setTracking(true);
  };

  // (Re)starts background location in a mode; calling it again while
  // tracking just changes the settings (Auto switching on charge).
  const startUpdates = async (mode: 'high' | 'balanced' | 'saver') => {
    activeModeRef.current = mode;
    await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
      ...locationOptions(mode),
      activityType: Location.ActivityType.AutomotiveNavigation,
      pausesUpdatesAutomatically: false,
      showsBackgroundLocationIndicator: true,
      foregroundService: { notificationTitle: 'tarmacked is tracking', notificationBody: 'Recording this drive' },
    });
    addLog(`GPS mode: ${mode}`);
  };

  const chooseAccuracy = (mode: AccuracyMode) => {
    setAccuracyMode(mode);
    store.setMeta('accuracy_mode', mode).catch(() => undefined);
  };

  const stop = async () => {
    if (batterySub.current) {
      batterySub.current.remove();
      batterySub.current = null;
    }
    try {
      await Location.stopLocationUpdatesAsync(LOCATION_TASK_NAME);
    } catch {
      // wasn't running as a background task
    }
    if (foregroundSub.current) {
      foregroundSub.current.remove();
      foregroundSub.current = null;
    }
    const newPoints = recordedPoints.slice(processedIndexRef.current);
    processedIndexRef.current = recordedPoints.length;
    processPoints(newPoints);
    const matcher = matcherRef.current;
    let ignored = 0;
    let driveRoads: string[] = [];
    if (matcher) {
      const done = matcher.finish();
      // Start/stop credit comes after the completed sections, so a section
      // finished this drive replaces any stretch of it.
      const { newM } = markDriven([...done, ...matcher.stubs]);
      driveNewMRef.current += newM;
      savePartialsFrom(matcher);
      ignored = matcher.gps.ignored;
      driveRoads = matcher.roadsCovered();
    }
    matcherRef.current = null;
    const driveId = currentDriveIdRef.current;
    if (driveId !== null) {
      if (recordedPoints.length < 2) {
        store.deleteDrive(driveId).catch(() => undefined); // nothing recorded
        setRawStats((prev) => ({ ...prev, drives: Math.max(0, prev.drives - 1) }));
      } else {
        store
          .setDriveStats([
            { id: driveId, endedAt: Date.now(), distanceM: driveDistanceRef.current, newM: driveNewMRef.current, ignoredN: ignored },
          ])
          .catch(() => undefined);
        store
          .setDriveRoads(driveId, driveRoads)
          .then(() => store.loadRoadCounts())
          .then(setRoadCounts)
          .catch(() => undefined);
        const patchy = isPatchy(ignored, recordedPoints.length);
        setNote(
          `Drive saved: ${km(driveDistanceRef.current)} km, ${km(driveNewMRef.current)} km of new road.` +
            (patchy ? ' ⚠ Patchy GPS on this drive — check it in Drives.' : '')
        );
      }
    }
    currentDriveIdRef.current = null;
    setTracking(false);
    setLiveIds([]);
    setLiveTrail([]);
    if (drives !== null) store.listDrives().then(setDrives).catch(() => undefined);
  };

  const onMapPress = (e: MapPressEvent) => {
    if (!tracking || editMode || !simulateTaps) return;
    const { latitude, longitude } = e.nativeEvent.coordinate;
    recordedPoints.push({ latitude, longitude, timestamp: Date.now() });
  };

  // ---------- Editing ----------

  const handleEditTap = (id: string) => {
    if (editAction === 'undrive') {
      // The tapped road piece, and any sections of it.
      const gone = Array.from(drivenRef.current).filter((d) => baseChunkId(d) === id);
      if (gone.length === 0) return;
      for (const d of gone) {
        drivenRef.current.delete(d);
        forgetDriven(d);
        store.removeDriven(d).catch((e) => setNote(`Couldn't save that change: ${(e as Error).message}`));
      }
      unmarkedRef.current.set(id, Date.now());
      setDrivenIds(new Set(drivenRef.current));
      store.markUnmarked(id).catch(() => undefined);
      return;
    }
    const nowExcluded = !excludedRef.current.has(id);
    const seg = netRef.current.segs.get(id);
    const info = { c: seg?.c ?? null, l: seg ? lineLengthMeters(seg.coords) : null };
    if (nowExcluded) {
      excludedRef.current.add(id);
      excludedInfoRef.current.set(id, info);
    } else {
      excludedRef.current.delete(id);
      excludedInfoRef.current.delete(id);
    }
    setExcludedIds(new Set(excludedRef.current));
    store.setExcluded(id, nowExcluded, info.c, info.l).catch((e) => setNote(`Couldn't save that change: ${(e as Error).message}`));
  };

  // ---------- Map helpers ----------

  const recentre = async () => {
    setFollowing(true);
    try {
      const pos =
        (await Location.getLastKnownPositionAsync()) ??
        (await withTimeout(Location.getCurrentPositionAsync({}), 8000, 'get current position'));
      mapRef.current?.animateCamera({ center: { latitude: pos.coords.latitude, longitude: pos.coords.longitude } }, { duration: 400 });
    } catch {
      // no fix right now — following snaps to you on the next update anyway
    }
  };

  // ---------- Drives ----------

  const openDrives = async () => {
    setPanel((p) => (p === 'drives' ? null : 'drives'));
    try {
      setDrives(await store.listDrives());
    } catch (e) {
      setNote(`Couldn't load drives: ${(e as Error).message}`);
    }
  };

  const showDrive = async (id: number) => {
    setDeleteConfirmId(null);
    if (selectedDrive?.id === id) {
      setSelectedDrive(null);
      return;
    }
    try {
      const points = await store.loadDrivePoints(id);
      const roads = await store.loadDriveRoads(id);
      setSelectedDrive({ id, points, roads });
      setHighlight(null);
      if (points.length > 1) {
        setFollowing(false);
        mapRef.current?.fitToCoordinates(
          points.map((p) => ({ latitude: p.latitude, longitude: p.longitude })),
          { edgePadding: { top: 120, right: 40, bottom: 320, left: 40 }, animated: true }
        );
      }
    } catch (e) {
      setNote(`Couldn't load that drive: ${(e as Error).message}`);
    }
  };

  const deleteDrive = async (id: number) => {
    if (deleteConfirmId !== id) {
      setDeleteConfirmId(id);
      return;
    }
    setDeleteConfirmId(null);
    if (selectedDrive?.id === id) setSelectedDrive(null);
    try {
      // Remember its trail until the re-check has removed the roads it earned.
      const gone = await store.loadDrivePoints(id);
      let forgotten: Point[][] = [];
      try {
        forgotten = JSON.parse((await store.getMeta('forgotten_trails')) || '[]');
      } catch {
        forgotten = [];
      }
      await store.setMeta('forgotten_trails', JSON.stringify([...forgotten, gone]));
      await store.deleteDrive(id);
      setDrives(await store.listDrives());
      const ok = await runRecheck('deleted');
      if (!ok) setNote('Drive deleted. Its roads will be re-checked once road data can be downloaded.');
    } catch (e) {
      setNote(`Couldn't delete that drive: ${(e as Error).message}`);
    }
  };

  // Leave a patchy drive out (it earns no roads) or put it back in.
  const toggleLeftOut = async (d: store.DriveSummary) => {
    try {
      await store.setDriveLeftOut(d.id, !d.leftOut);
      setDrives(await store.listDrives());
      const ok = await runRecheck('manual');
      if (!ok) setNote(`Drive ${d.leftOut ? 'included' : 'left out'} — roads update once road data can be downloaded.`);
    } catch (e) {
      setNote(`Couldn't change that drive: ${(e as Error).message}`);
    }
  };

  // ---------- Stats: roads ----------

  // Jumps to a road's most-driven bit, with the heatmap on so the colours
  // match the list.
  const showRoad = (r: RoadRank) => {
    const shapes = r.hotChunks.map((id) => netRef.current.shapeOf(id)).filter((c): c is Coord[] => !!c);
    if (shapes.length === 0) return;
    setHighlight({ name: r.name, count: r.count, chunks: r.hotChunks });
    setSelectedDrive(null);
    setHeatOn(true);
    setPanel(null);
    setFollowing(false);
    // Zoom to the longest joined-up stretch at that count.
    const chains = buildChains(r.hotChunks, (id) => netRef.current.shapeOf(id) ?? undefined);
    const longest = chains.reduce((a, b) => (lineLengthMeters(b.coords) > lineLengthMeters(a.coords) ? b : a), chains[0]);
    mapRef.current?.fitToCoordinates(toLatLng(longest.coords), {
      edgePadding: { top: 160, right: 60, bottom: 220, left: 60 },
      animated: true,
    });
  };

  // ---------- Dev tools ----------

  const toggleRawTrail = async () => {
    if (rawSessions) {
      setRawSessions(null);
      return;
    }
    try {
      setRawSessions((await store.loadDrives()).map((d) => d.points));
    } catch (e) {
      setNote(`Couldn't load the saved trail: ${(e as Error).message}`);
    }
  };

  const undoRecheck = async () => {
    try {
      const n = await store.restoreRemoved();
      const data = await store.loadAll();
      for (const d of data.driven) {
        if (!drivenRef.current.has(d.id)) {
          drivenRef.current.add(d.id);
          rememberDriven(d.id, d.shape, d.county);
          unmarkedRef.current.delete(d.id);
        }
      }
      setDrivenIds(new Set(drivenRef.current));
      setRemovedCount(0);
      setNote(`Put back ${n} road pieces.`);
    } catch (e) {
      setNote(`Couldn't put them back: ${(e as Error).message}`);
    }
  };

  // Swaps cached road data for fresh data (after the tiles are regenerated).
  const refreshRoadData = async () => {
    if (refreshing) return;
    setRefreshing(true);
    setPanel(null);
    netRef.current.clear();
    knownTilesRef.current.clear();
    setNetRev((r) => r + 1);
    try {
      await store.clearTiles();
      if (homeCounty) {
        setNote(`Refreshing road data for ${homeCounty}…`);
        const ok = await downloadHomeCounty(homeCounty);
        setNote(ok ? 'Road data refreshed. Other areas re-download as you drive.' : 'Refresh failed — check your connection.');
      } else {
        setNote('Road data cleared. Areas re-download as you drive.');
      }
    } finally {
      setRefreshing(false);
    }
  };

  const confirmThen = (what: 'reset' | 'uninstall', action: () => void) => {
    if (confirming !== what) {
      setConfirming(what);
      setTimeout(() => setConfirming((c) => (c === what ? null : c)), 4000);
      return;
    }
    setConfirming(null);
    action();
  };

  const uninstallAreas = () => {
    netRef.current.clear();
    knownTilesRef.current.clear();
    setNetRev((r) => r + 1);
    store.clearTiles().catch(() => undefined);
    setPanel(null);
  };

  const resetMap = () => {
    drivenRef.current = new Set();
    excludedRef.current = new Set();
    drivenShapesRef.current = new Map();
    drivenCountyRef.current = new Map();
    lengthRef.current = new Map();
    excludedInfoRef.current = new Map();
    unmarkedRef.current = new Map();
    partialsRef.current = new Map();
    setRoadCounts(new Map());
    setHighlight(null);
    setDrivenIds(new Set());
    setExcludedIds(new Set());
    setUnmatchedCount(0);
    setRawSessions(null);
    setRawStats({ drives: 0, points: 0 });
    setRemovedCount(0);
    setSelectedDrive(null);
    setDrives([]);
    store.resetProgress().catch((e) => setNote(`Reset failed: ${(e as Error).message}`));
    setPanel(null);
  };

  // ---------- Backup & restore ----------

  const exportBackup = async () => {
    if (backupBusy) return;
    setBackupBusy(true);
    try {
      const data = await store.exportBackup();
      const file = new File(Paths.cache, `tarmacked-backup-${new Date().toISOString().slice(0, 10)}.json`);
      if (file.exists) file.delete();
      file.create();
      file.write(JSON.stringify(data));
      if (!(await Sharing.isAvailableAsync())) throw new Error('sharing is not available on this device');
      await Sharing.shareAsync(file.uri, { mimeType: 'application/json', UTI: 'public.json', dialogTitle: 'Save your tarmacked backup' });
      setNote(`Backup created: ${data.driven.length} road pieces, ${data.drives.length} drives.`);
    } catch (e) {
      setNote(`Backup failed: ${(e as Error).message}`);
    } finally {
      setBackupBusy(false);
    }
  };

  const restoreBackup = async () => {
    if (backupBusy || tracking) return;
    setBackupBusy(true);
    try {
      const picked = await DocumentPicker.getDocumentAsync({ type: 'application/json', copyToCacheDirectory: true });
      if (picked.canceled || !picked.assets?.length) return;
      const text = await new File(picked.assets[0].uri).text();
      const result = await store.importBackup(JSON.parse(text));
      const data = await store.loadAll();
      for (const d of data.driven) {
        drivenRef.current.add(d.id);
        rememberDriven(d.id, drivenShapesRef.current.get(d.id) ?? d.shape, d.county);
      }
      for (const e of data.excluded) {
        excludedRef.current.add(e.id);
        excludedInfoRef.current.set(e.id, { c: e.county, l: e.lengthM });
      }
      unmarkedRef.current = await store.loadUnmarked();
      backfillFromSegments(Array.from(netRef.current.segs.values()));
      setDrivenIds(new Set(drivenRef.current));
      setExcludedIds(new Set(excludedRef.current));
      setUnmatchedCount(data.unmatched.length);
      setRawStats({ drives: data.driveCount, points: data.pointCount });
      if (data.homeCounty) setHomeCounty(data.homeCounty);
      setPanel(null);
      setNote(`Restored: ${result.driven} road pieces merged in, ${result.drivesAdded} new drives. Nothing on the phone was removed.`);
      if (result.drivesAdded > 0) runRecheck('manual'); // fills in heatmap counts for the restored drives
    } catch (e) {
      setNote(`Restore failed: ${(e as Error).message}`);
    } finally {
      setBackupBusy(false);
    }
  };

  // ---------- Stats ----------

  // Per-county and national figures. Totals come from county-stats.json;
  // driven km uses each driven road's stored shape and county. Excluded
  // roads come off both sides.
  const countyFigures = useMemo(() => {
    const n = countyStats?.counties.length ?? 0;
    const driven = new Array(n).fill(0);
    const excluded = new Array(n).fill(0);
    drivenIds.forEach((id) => {
      const base = baseChunkId(id);
      if (excludedIds.has(base)) return;
      if (base !== id && drivenIds.has(base)) return; // whole piece already counted
      const c = drivenCountyRef.current.get(id);
      if (c === undefined || c >= n) return;
      driven[c] += lengthRef.current.get(id) ?? 0;
    });
    excludedIds.forEach((id) => {
      const info = excludedInfoRef.current.get(id);
      if (info && info.c !== null && info.c < n && info.l !== null) excluded[info.c] += info.l;
    });
    const rows = (countyStats?.counties ?? []).map((name, i) => {
      const total = Math.max(0, countyStats!.totalMeters[i] - excluded[i]);
      return { code: i, name, driven: driven[i], total, percent: total > 0 ? (driven[i] / total) * 100 : 0 };
    });
    const nationalDriven = driven.reduce((a: number, b: number) => a + b, 0);
    const nationalTotal = Math.max(0, (countyStats?.nationalMeters ?? 0) - excluded.reduce((a: number, b: number) => a + b, 0));
    const unassigned = Array.from(drivenIds).filter((id) => !drivenCountyRef.current.has(id)).length;
    return { rows, nationalDriven, nationalTotal, nationalPercent: nationalTotal > 0 ? (nationalDriven / nationalTotal) * 100 : 0, unassigned };
  }, [countyStats, drivenIds, excludedIds]);

  const focusRow =
    currentCounty !== null ? countyFigures.rows[currentCounty] : countyFigures.rows.find((r) => r.name === homeCounty) ?? null;

  // ---------- Map drawing ----------

  const bounds = useMemo(() => {
    const padLat = visibleRegion.latitudeDelta * 0.6;
    const padLon = visibleRegion.longitudeDelta * 0.6;
    return {
      minLat: visibleRegion.latitude - padLat,
      maxLat: visibleRegion.latitude + padLat,
      minLon: visibleRegion.longitude - padLon,
      maxLon: visibleRegion.longitude + padLon,
    };
  }, [visibleRegion]);
  const inView = (c: Chain) => c.maxLat >= bounds.minLat && c.minLat <= bounds.maxLat && c.maxLon >= bounds.minLon && c.minLon <= bounds.maxLon;

  // Driven roads joined into long continuous lines (far fewer map objects
  // than one per 100m piece), then simplified to the detail the current
  // zoom can actually show.
  const drivenChains = useMemo(
    () =>
      buildChains(
        Array.from(drivenIds).filter((id) => !excludedIds.has(baseChunkId(id))),
        (id) => drivenShapesRef.current.get(id)
      ),
    [drivenIds, excludedIds]
  );
  // Tolerance steps in powers of two so panning doesn't re-simplify.
  const simplifyLevel = Math.max(0, Math.round(Math.log2(visibleRegion.latitudeDelta / 0.005)));
  const simplifiedChains = useMemo(() => {
    if (simplifyLevel === 0) return drivenChains;
    const tolerance = (0.005 * 2 ** simplifyLevel) / 700; // ~1 screen pixel, in degrees
    return drivenChains.map((c) => ({ ...c, coords: simplifyLine(c.coords, tolerance) }));
  }, [drivenChains, simplifyLevel]);
  const visibleChains = useMemo(() => simplifiedChains.filter(inView), [simplifiedChains, bounds]); // eslint-disable-line react-hooks/exhaustive-deps
  const zoomedOut = visibleRegion.latitudeDelta > 0.3;

  // Heatmap: driven roads grouped into colour steps by how many drives
  // covered them, each step joined into lines like the plain green.
  const maxCount = useMemo(() => {
    let m = 1;
    roadCounts.forEach((n) => {
      if (n > m) m = n;
    });
    return m;
  }, [roadCounts]);
  const heatChains = useMemo(() => {
    if (!heatOn) return [] as Chain[][];
    const steps: string[][] = Array.from({ length: HEAT_STEPS }, () => []);
    drivenIds.forEach((id) => {
      if (excludedIds.has(baseChunkId(id))) return;
      steps[heatStep(roadCounts.get(baseChunkId(id)) ?? 1, maxCount)].push(id);
    });
    return steps.map((ids) => buildChains(ids, (id) => drivenShapesRef.current.get(id)));
  }, [heatOn, drivenIds, excludedIds, roadCounts, maxCount]);
  const visibleHeat = useMemo(() => {
    const tolerance = simplifyLevel === 0 ? 0 : (0.005 * 2 ** simplifyLevel) / 700;
    return heatChains.map((chains) =>
      chains.filter(inView).map((c) => (tolerance ? { ...c, coords: simplifyLine(c.coords, tolerance) } : c))
    );
  }, [heatChains, simplifyLevel, bounds]); // eslint-disable-line react-hooks/exhaustive-deps

  // The selected drive's roads (orange), and a most-driven stretch picked
  // from Stats → Roads.
  const shapeForDraw = (id: string) => drivenShapesRef.current.get(id) ?? netRef.current.shapeOf(id) ?? undefined;
  const selectedChains = useMemo(
    () => (selectedDrive ? buildChains(selectedDrive.roads, shapeForDraw) : []),
    [selectedDrive, netRev] // eslint-disable-line react-hooks/exhaustive-deps
  );
  const highlightChains = useMemo(
    () => (highlight ? buildChains(highlight.chunks, shapeForDraw) : []),
    [highlight, netRev] // eslint-disable-line react-hooks/exhaustive-deps
  );

  // ---------- Stats figures ----------

  const roadRanking = useMemo(
    () => (panel === 'stats' && statsTab === 'roads' ? rankRoads(netRef.current, roadCounts) : []),
    [panel, statsTab, roadCounts, netRev]
  );
  const overview = useMemo(() => {
    const list = (drives ?? []).filter((d) => !d.leftOut);
    const now = new Date();
    const weekStart = new Date(now.getFullYear(), now.getMonth(), now.getDate() - ((now.getDay() + 6) % 7)).getTime();
    const monthStart = new Date(now.getFullYear(), now.getMonth(), 1).getTime();
    let week = 0, month = 0, all = 0, dist = 0, time = 0;
    let longest: store.DriveSummary | null = null;
    let mostNew: store.DriveSummary | null = null;
    for (const d of list) {
      const n = d.newM ?? 0;
      all += n;
      if (d.startedAt >= weekStart) week += n;
      if (d.startedAt >= monthStart) month += n;
      dist += d.distanceM ?? 0;
      if (d.endedAt) time += d.endedAt - d.startedAt;
      if ((d.distanceM ?? 0) > (longest?.distanceM ?? 0)) longest = d;
      if (n > (mostNew?.newM ?? 0)) mostNew = d;
    }
    return { count: list.length, week, month, all, dist, time, longest, mostNew };
  }, [drives]);
  const topRoad = useMemo(
    () => (panel === 'stats' && statsTab === 'overview' ? rankRoads(netRef.current, roadCounts, 1)[0] ?? null : null),
    [panel, statsTab, roadCounts, netRev]
  );

  // Roads completed during the drive in progress, drawn live on top.
  const liveChains = useMemo(() => buildChains(liveIds, (id) => drivenShapesRef.current.get(id)), [liveIds]);

  const editZoomedIn = visibleRegion.latitudeDelta <= EDIT_MAX_LAT_DELTA;
  // Road pieces with anything driven on them (whole or in sections), for edit mode.
  const drivenBases = useMemo(() => new Set(Array.from(drivenIds).map(baseChunkId)), [drivenIds]);
  const visibleEditSegments = useMemo(() => {
    if (!editMode || !editZoomedIn) return [] as RoadSegment[];
    return netRef.current.inBox(bounds.minLat, bounds.minLon, bounds.maxLat, bounds.maxLon);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [editMode, editZoomedIn, bounds, netRev]);

  // Every dark outline is drawn first and every green line after, so no
  // outline ever sits on top of green where two lines meet. Apple Maps
  // stacks lines in the order they're added (it ignores zIndex), so the
  // whole set is re-added whenever it changes to keep that order.
  const drawRevs = useRef({ n: 0, map: new WeakMap<Chain[], number>() });
  // A new number only when this set of lines actually changes.
  const revOf = (chains: Chain[]) => {
    const revs = drawRevs.current;
    let rev = revs.map.get(chains);
    if (rev === undefined) {
      rev = ++revs.n;
      revs.map.set(chains, rev);
    }
    return rev;
  };
  type Layer = { chains: Chain[]; color: string };
  // `after`: revision of the lines drawn underneath. Lines drawn on top
  // include it in their keys, so they're re-added (back on top) whenever
  // the lines under them are.
  const drawLayers = (prefix: string, layers: Layer[], thin: boolean, after = '', outline = '#0d3818', width = 4) => {
    const tag = (c: Chain[]) => `${revOf(c)}${after}`;
    const outlines = thin
      ? []
      : layers.flatMap((l, li) =>
          l.chains.map((c, i) => (
            <Polyline
              key={`${prefix}o${li}.${i}-${tag(l.chains)}`}
              coordinates={toLatLng(c.coords)}
              strokeColor={outline}
              strokeWidth={width + 3}
              lineCap="round"
              lineJoin="round"
            />
          ))
        );
    const cores = layers.flatMap((l, li) =>
      l.chains.map((c, i) => (
        <Polyline
          key={`${prefix}c${li}.${i}-${tag(l.chains)}`}
          coordinates={toLatLng(c.coords)}
          strokeColor={l.color}
          strokeWidth={thin ? width - 1 : width}
          lineCap="round"
          lineJoin="round"
        />
      ))
    );
    return [...outlines, ...cores];
  };
  const baseLayers: Layer[] = heatOn
    ? visibleHeat.map((chains, i) => ({ chains, color: stepColor(i) }))
    : [{ chains: visibleChains, color: '#39d353' }];
  // Everything drawn on top is re-added when the base lines or map type change.
  const baseRev = `m${mapTypeIndex}b${editMode ? 'e' : baseLayers.map((l) => revOf(l.chains)).join('.')}`;

  // ---------- Onboarding ----------

  if (onboarded === null) {
    return (
      <View style={styles.onboardContainer}>
        <ActivityIndicator color="#39d353" size="large" />
        <Text style={[styles.onboardText, { marginTop: 16 }]}>{bootStep}</Text>
      </View>
    );
  }

  if (onboarded === false) {
    return (
      <View style={styles.onboardContainer}>
        <Text style={styles.onboardTitle}>tarmacked</Text>
        {downloadingCounty ? (
          <>
            <Text style={styles.onboardText}>Downloading {downloadingCounty}…</Text>
            <ActivityIndicator color="#39d353" size="large" style={{ marginVertical: 16 }} />
            <Text style={styles.onboardText}>
              {downloadProgress.done} / {downloadProgress.total} tiles
            </Text>
          </>
        ) : (
          <>
            <Text style={styles.onboardText}>
              Pick your home county to download it now — everywhere else downloads automatically as you drive there.
            </Text>
            {onboardingError ? <Text style={styles.onboardError}>{onboardingError}</Text> : null}
            {onboardingCounties === null && !onboardingError && (
              <ActivityIndicator color="#39d353" size="large" style={{ marginVertical: 16 }} />
            )}
            <ScrollView style={styles.countyList}>
              {(onboardingCounties || []).map((c) => (
                <Pressable key={c} style={styles.countyRow} onPress={() => downloadHomeCounty(c)}>
                  <Text style={styles.countyRowText}>{c}</Text>
                </Pressable>
              ))}
            </ScrollView>
            <Pressable style={styles.skipLink} onPress={skipOnboarding}>
              <Text style={styles.linkText}>Skip for now</Text>
            </Pressable>
          </>
        )}
      </View>
    );
  }

  // ---------- Main screen ----------

  const elapsed = tracking ? Date.now() - driveStartRef.current : 0;
  const togglePanel = (p: Panel) => setPanel((cur) => (cur === p ? null : p));

  return (
    <View style={styles.container}>
      <MapView
        ref={mapRef}
        style={styles.map}
        provider={PROVIDER_DEFAULT}
        mapType={MAP_TYPES[mapTypeIndex] === 'osm' ? 'standard' : (MAP_TYPES[mapTypeIndex] as MapType)}
        showsPointsOfInterest={MAP_TYPES[mapTypeIndex] !== 'osm'}
        initialRegion={region}
        showsUserLocation
        followsUserLocation={following && !editMode}
        onPanDrag={() => following && setFollowing(false)}
        onPress={onMapPress}
        onRegionChangeComplete={(r) => setVisibleRegion(r)}
      >
        {MAP_TYPES[mapTypeIndex] === 'osm' && (
          <UrlTile
            key="osm"
            urlTemplate={OSM_TILE_URL}
            maximumZ={19}
            shouldReplaceMapContent
            tileCachePath={`${Paths.cache.uri}osm-tiles`}
            tileCacheMaxAge={7 * 24 * 60 * 60}
          />
        )}
        {editMode &&
          visibleEditSegments.map((seg) => {
            const isExcluded = excludedIds.has(seg.id);
            const isDriven = drivenBases.has(seg.id);
            return (
              <Polyline
                key={seg.id}
                coordinates={toLatLng(seg.coords)}
                strokeColor={isExcluded ? '#a03030' : isDriven ? '#39d353' : '#555'}
                strokeWidth={isExcluded || isDriven ? 5 : 3}
                lineCap="round"
                lineJoin="round"
                lineDashPattern={isExcluded ? [6, 4] : undefined}
                tappable
                onPress={() => handleEditTap(seg.id)}
              />
            );
          })}

        {!editMode && drawLayers('d', baseLayers, zoomedOut, `m${mapTypeIndex}`)}

        {tracking && drawLayers('live', [{ chains: liveChains, color: '#39d353' }], false, baseRev)}

        {tracking && liveTrail.length > 1 && (
          <Polyline
            coordinates={liveTrail.map((p) => ({ latitude: p.latitude, longitude: p.longitude }))}
            strokeColor="#3a8dff"
            strokeWidth={3}
            lineCap="round"
            lineJoin="round"
            zIndex={6}
          />
        )}

        {/* Selected drive: its roads in orange, on top of everything else. */}
        {selectedDrive && selectedChains.length > 0 && drawLayers('sel', [{ chains: selectedChains, color: '#ff9f1a' }], false, baseRev, '#5a3000')}
        {/* Drives from before v0.14's re-check have no road list yet: show the GPS trail. */}
        {selectedDrive && selectedChains.length === 0 && selectedDrive.points.length > 1 && (
          <Polyline
            key={`seltrail-${baseRev}`}
            coordinates={selectedDrive.points.map((p) => ({ latitude: p.latitude, longitude: p.longitude }))}
            strokeColor="#ff9f1a"
            strokeWidth={4}
            lineCap="round"
            lineJoin="round"
            zIndex={7}
          />
        )}

        {/* Most-driven stretch picked from Stats → Roads. */}
        {highlight && drawLayers('hl', [{ chains: highlightChains, color: '#ffffff' }], false, baseRev, '#d0206a', 5)}

        {rawSessions &&
          rawSessions.map((session, i) =>
            session.length > 1 ? (
              <Polyline
                key={`raw-${i}`}
                coordinates={session.map((p) => ({ latitude: p.latitude, longitude: p.longitude }))}
                strokeColor="#3a8dff"
                strokeWidth={2}
                zIndex={8}
              />
            ) : null
          )}
      </MapView>

      {/* Top bar */}
      <View style={styles.topBar}>
        <View style={styles.topGroup}>
          <Pressable
            style={[styles.chip, panel === 'stats' && styles.chipActive]}
            onPress={() => {
              togglePanel('stats');
              store.listDrives().then(setDrives).catch(() => undefined);
            }}
          >
            <Text style={styles.chipText}>Stats</Text>
          </Pressable>
          <Pressable style={[styles.chip, panel === 'drives' && styles.chipActive]} onPress={openDrives}>
            <Text style={styles.chipText}>Drives</Text>
          </Pressable>
          <Pressable style={[styles.chip, panel === 'dev' && styles.chipActive]} onPress={() => togglePanel('dev')}>
            <Text style={styles.chipText}>⚙</Text>
          </Pressable>
        </View>
        <View style={styles.topGroup}>
          <Pressable style={[styles.chip, heatOn && styles.chipHeat]} onPress={() => setHeatOn((v) => !v)}>
            <Text style={styles.chipText}>Heat</Text>
          </Pressable>
          <Pressable
            style={styles.chip}
            onPress={() => {
              const next = (mapTypeIndex + 1) % MAP_TYPES.length;
              setMapTypeIndex(next);
              store.setMeta('map_type', MAP_TYPES[next]).catch(() => undefined);
            }}
          >
            <Text style={styles.chipText}>{MAP_LABELS[MAP_TYPES[mapTypeIndex]]}</Text>
          </Pressable>
        </View>
      </View>

      {/* Heatmap legend, and the picked most-driven stretch */}
      {(heatOn || highlight) && !panel && !editMode && (
        <View style={styles.heatBar}>
          {heatOn && (
            <View style={styles.legendRow}>
              <Text style={styles.legendText}>1×</Text>
              {Array.from({ length: HEAT_STEPS }, (_, i) => (
                <View key={i} style={[styles.legendStep, { backgroundColor: stepColor(i) }]} />
              ))}
              <Text style={styles.legendText}>{maxCount}×</Text>
            </View>
          )}
          {highlight && (
            <Pressable style={styles.legendRow} onPress={() => setHighlight(null)}>
              <Text style={styles.highlightText} numberOfLines={1}>
                {highlight.name} · {highlight.count}× — most driven bit
              </Text>
              <Text style={styles.legendText}>  ✕</Text>
            </Pressable>
          )}
        </View>
      )}

      {/* Messages */}
      {recheckProgress !== null ? (
        <View style={styles.toast}>
          <Text style={styles.toastText}>Re-checking your drives… {Math.round(recheckProgress * 100)}%</Text>
        </View>
      ) : note ? (
        <Pressable style={styles.toast} onPress={() => setNote('')}>
          <Text style={styles.toastText}>{note}</Text>
        </Pressable>
      ) : null}

      {/* Stats */}
      {panel === 'stats' && (
        <View style={styles.panel}>
          <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.tabBar} contentContainerStyle={{ gap: 6 }}>
            {STATS_TABS.map((t) => (
              <Pressable key={t.key} style={[styles.tabPill, statsTab === t.key && styles.tabPillActive]} onPress={() => setStatsTab(t.key)}>
                <Text style={styles.chipText}>{t.label}</Text>
              </Pressable>
            ))}
          </ScrollView>
          <ScrollView>
            {statsTab === 'overview' &&
              (countyStats ? (
                <>
                  <Text style={styles.bigStat}>{countyFigures.nationalPercent.toFixed(3)}%</Text>
                  <Text style={styles.small}>
                    of Ireland's roads · {km(countyFigures.nationalDriven)} / {km(countyFigures.nationalTotal, 0)} km
                  </Text>
                  <Text style={styles.sectionTitle}>New road</Text>
                  <View style={styles.statGrid}>
                    <StatTile label="This week" value={`+${km(overview.week)} km`} />
                    <StatTile label="This month" value={`+${km(overview.month)} km`} />
                    <StatTile label="All time" value={`${km(overview.all)} km`} />
                  </View>
                  <Text style={styles.sectionTitle}>Drives</Text>
                  <View style={styles.statGrid}>
                    <StatTile label="Drives" value={String(overview.count)} />
                    <StatTile label="Distance" value={`${km(overview.dist, 0)} km`} />
                    <StatTile label="Time" value={formatDuration(overview.time)} />
                  </View>
                  <Text style={styles.sectionTitle}>Records</Text>
                  {overview.longest && (
                    <Text style={styles.recordLine}>
                      Longest drive: {km(overview.longest.distanceM ?? 0)} km · {formatWhen(overview.longest.startedAt)}
                    </Text>
                  )}
                  {overview.mostNew && (
                    <Text style={styles.recordLine}>
                      Most new road: +{km(overview.mostNew.newM ?? 0)} km · {formatWhen(overview.mostNew.startedAt)}
                    </Text>
                  )}
                  {topRoad && (
                    <Pressable onPress={() => showRoad(topRoad)}>
                      <Text style={styles.recordLine}>
                        Most driven road: {topRoad.name} · {topRoad.count}× <Text style={styles.linkText}>show</Text>
                      </Text>
                    </Pressable>
                  )}
                  {!overview.longest && !topRoad && <Text style={styles.small}>Records appear after your first drive.</Text>}
                </>
              ) : (
                <Text style={styles.small}>Road totals haven't loaded yet — connect to the internet once and they're saved for offline use.</Text>
              ))}

            {statsTab === 'counties' &&
              (countyStats ? (
                <>
                  <Text style={styles.statsHeadline}>
                    Ireland {countyFigures.nationalPercent.toFixed(3)}% · {km(countyFigures.nationalDriven)} /{' '}
                    {km(countyFigures.nationalTotal, 0)} km
                  </Text>
                  {countyFigures.rows.map((r) => (
                    <View key={r.name} style={[styles.countyStatRow, r.code === focusRow?.code && styles.countyStatRowCurrent]}>
                      <Text style={[styles.countyStatName, r.driven > 0 && styles.countyStatNameDriven]}>{shortCounty(r.name)}</Text>
                      <Text style={styles.countyStatValue}>
                        {r.percent.toFixed(2)}% · {km(r.driven)} / {km(r.total, 0)} km
                      </Text>
                    </View>
                  ))}
                  {countyFigures.unassigned > 0 && (
                    <Text style={styles.small}>
                      {countyFigures.unassigned} road pieces aren't counted yet — their county fills in once the road data for
                      that area downloads.
                    </Text>
                  )}
                </>
              ) : (
                <Text style={styles.small}>Road totals haven't loaded yet — connect to the internet once and they're saved for offline use.</Text>
              ))}

            {statsTab === 'roads' && (
              <>
                <Text style={styles.small}>
                  Your most driven roads — the number is how many drives covered the busiest bit. Tap one to see it on the map
                  (colours match the heatmap).
                </Text>
                {roadRanking.length === 0 ? (
                  <Text style={styles.small}>Nothing yet — this fills in as you drive.</Text>
                ) : (
                  roadRanking.map((r, i) => (
                    <Pressable key={r.key} style={styles.roadRow} onPress={() => showRoad(r)}>
                      <Text style={styles.roadRank}>{i + 1}</Text>
                      <View style={[styles.roadSwatch, { backgroundColor: stepColor(heatStep(r.count, maxCount)) }]} />
                      <View style={{ flex: 1 }}>
                        <Text style={styles.roadName} numberOfLines={1}>
                          {r.name}
                        </Text>
                        <Text style={styles.driveInfo}>
                          {r.county !== null && countyStats ? `${shortCounty(countyStats.counties[r.county] ?? '')} · ` : ''}
                          {km(r.hotM, 2)} km at that
                        </Text>
                      </View>
                      <Text style={styles.roadCount}>{r.count}×</Text>
                    </Pressable>
                  ))
                )}
              </>
            )}

            {statsTab === 'data' && (
              <>
                <Text style={styles.small}>
                  Saved on this phone. Back up to keep a copy somewhere safe (Files, iCloud Drive, email). Restoring merges a backup
                  in — it never removes anything already on the phone.
                </Text>
                <View style={styles.row}>
                  <Pressable style={[styles.button, styles.buttonBlue]} onPress={exportBackup} disabled={backupBusy}>
                    <Text style={styles.buttonText}>{backupBusy ? 'Working…' : 'Back up'}</Text>
                  </Pressable>
                  <Pressable style={[styles.button, styles.buttonGrey]} onPress={restoreBackup} disabled={backupBusy || tracking}>
                    <Text style={styles.buttonText}>Restore</Text>
                  </Pressable>
                </View>
              </>
            )}
          </ScrollView>
        </View>
      )}

      {/* Drives */}
      {panel === 'drives' && (
        <View style={styles.panel}>
          <Text style={styles.panelTitle}>Drives</Text>
          {drives === null ? (
            <ActivityIndicator color="#39d353" />
          ) : drives.length === 0 ? (
            <Text style={styles.small}>No drives yet — tap Start when you set off.</Text>
          ) : (
            <ScrollView>
              {drives.map((d) => {
                const selected = selectedDrive?.id === d.id;
                const patchy = isPatchy(d.ignoredN, d.pointCount);
                return (
                  <Pressable key={d.id} style={[styles.driveRow, selected && styles.driveRowSelected]} onPress={() => showDrive(d.id)}>
                    <View style={{ flex: 1, opacity: d.leftOut ? 0.55 : 1 }}>
                      <Text style={styles.driveWhen}>
                        {formatWhen(d.startedAt)}
                        {patchy && <Text style={styles.patchyTag}>{'  ⚠ patchy GPS'}</Text>}
                        {d.leftOut && <Text style={styles.driveInfo}>{'  left out'}</Text>}
                      </Text>
                      <Text style={styles.driveInfo}>
                        {d.endedAt ? `${formatDuration(d.endedAt - d.startedAt)} · ` : ''}
                        {d.distanceM !== null ? `${km(d.distanceM)} km` : `${d.pointCount} points`}
                        {d.newM !== null && d.newM > 0 ? ` · +${km(d.newM)} km new` : ''}
                      </Text>
                    </View>
                    {selected && (patchy || d.leftOut) && (
                      <Pressable
                        style={[styles.smallButton, { marginRight: 6 }]}
                        onPress={() => toggleLeftOut(d)}
                        disabled={tracking || recheckProgress !== null}
                      >
                        <Text style={styles.chipText}>{d.leftOut ? 'Include' : 'Leave out'}</Text>
                      </Pressable>
                    )}
                    {selected && (
                      <Pressable
                        style={[styles.smallButton, deleteConfirmId === d.id && styles.smallButtonDanger]}
                        onPress={() => deleteDrive(d.id)}
                      >
                        <Text style={styles.chipText}>{deleteConfirmId === d.id ? 'Tap to confirm' : 'Delete'}</Text>
                      </Pressable>
                    )}
                  </Pressable>
                );
              })}
            </ScrollView>
          )}
          {selectedDrive && (
            <Text style={styles.small}>
              Its roads are shown in orange on the map. Tap it again to hide.
              {drives?.find((d) => d.id === selectedDrive.id && isPatchy(d.ignoredN, d.pointCount))
                ? ' Patchy GPS: some points were ignored. Its roads still count unless you leave it out.'
                : ''}
            </Text>
          )}
        </View>
      )}

      {/* Dev tools */}
      {panel === 'dev' && (
        <View style={styles.panel}>
          <ScrollView>
            <Text style={styles.panelTitle}>GPS accuracy</Text>
            <View style={[styles.row, { marginTop: 0 }]}>
              {ACCURACY_MODES.map((m) => (
                <Pressable
                  key={m.key}
                  style={[styles.smallButton, accuracyMode === m.key && styles.chipActive]}
                  onPress={() => chooseAccuracy(m.key)}
                >
                  <Text style={styles.chipText}>{m.label}</Text>
                </Pressable>
              ))}
            </View>
            <Text style={styles.small}>
              {ACCURACY_MODES.find((m) => m.key === accuracyMode)?.info}
              {tracking ? ' Applies from your next drive.' : ''}
            </Text>
            <Text style={[styles.panelTitle, { marginTop: 16 }]}>Developer tools</Text>
            <View style={styles.row}>
              <Pressable
                style={[styles.button, styles.buttonBlue]}
                disabled={tracking}
                onPress={() => {
                  setFollowing(false);
                  setEditMode(true);
                  setPanel(null);
                }}
              >
                <Text style={styles.buttonText}>Edit roads</Text>
              </Pressable>
              <Pressable
                style={[styles.button, styles.buttonPurple]}
                disabled={tracking || recheckProgress !== null}
                onPress={() => {
                  setPanel(null);
                  runRecheck('manual');
                }}
              >
                <Text style={styles.buttonText}>Re-check all drives</Text>
              </Pressable>
            </View>
            {removedCount > 0 && (
              <Pressable style={[styles.button, styles.buttonGrey]} onPress={undoRecheck} disabled={tracking}>
                <Text style={styles.buttonText}>Put back {removedCount} road pieces removed by re-checks</Text>
              </Pressable>
            )}
            <View style={styles.row}>
              <Pressable style={[styles.button, styles.buttonGrey, rawSessions && styles.buttonOn]} onPress={toggleRawTrail}>
                <Text style={styles.buttonText}>{rawSessions ? 'Hide' : 'Show'} raw GPS</Text>
              </Pressable>
            </View>
            <View style={styles.row}>
              <Pressable style={[styles.button, styles.buttonGrey, simulateTaps && styles.buttonOn]} onPress={() => setSimulateTaps((v) => !v)}>
                <Text style={styles.buttonText}>Tap-to-simulate: {simulateTaps ? 'on' : 'off'}</Text>
              </Pressable>
              <Pressable style={[styles.button, styles.buttonGrey]} onPress={refreshRoadData} disabled={tracking || refreshing}>
                <Text style={styles.buttonText}>{refreshing ? 'Refreshing…' : 'Refresh road data'}</Text>
              </Pressable>
            </View>
            <View style={styles.row}>
              <Pressable
                style={[styles.button, styles.buttonRed, confirming === 'uninstall' && styles.buttonRedConfirm]}
                onPress={() => confirmThen('uninstall', uninstallAreas)}
                disabled={tracking}
              >
                <Text style={styles.buttonText}>{confirming === 'uninstall' ? 'Tap again' : 'Clear road data'}</Text>
              </Pressable>
              <Pressable
                style={[styles.button, styles.buttonRed, confirming === 'reset' && styles.buttonRedConfirm]}
                onPress={() => confirmThen('reset', resetMap)}
                disabled={tracking}
              >
                <Text style={styles.buttonText}>{confirming === 'reset' ? 'Tap again to wipe' : 'Reset map'}</Text>
              </Pressable>
            </View>
            <Text style={styles.small}>
              Home county: {homeCounty || 'none'} · road pieces loaded: {netRef.current.size} · areas: {knownTilesRef.current.size}
              {'\n'}Driven: {drivenIds.size} · excluded: {excludedIds.size} · off-road GPS points: {unmatchedCount}
              {'\n'}Saved drives: {rawStats.drives} ({rawStats.points} points)
            </Text>
            <Text style={[styles.panelTitle, { marginTop: 12 }]}>Log</Text>
            <Text style={styles.logText}>{log.length ? log.join('\n') : '—'}</Text>
          </ScrollView>
        </View>
      )}

      {!following && !editMode && (
        <Pressable style={styles.recentreButton} onPress={recentre}>
          <Text style={styles.recentreText}>◎</Text>
        </Pressable>
      )}

      {/* Bottom bar */}
      {editMode ? (
        <View style={styles.bottomBar}>
          <View style={{ flex: 1 }}>
            <Text style={styles.barLine}>
              {!editZoomedIn
                ? 'Zoom in to edit roads'
                : editAction === 'exclude'
                  ? 'Tap a road: private / gone'
                  : 'Tap a green road to un-mark it'}
            </Text>
            <View style={[styles.row, { justifyContent: 'flex-start', marginTop: 6 }]}>
              <Pressable style={[styles.smallButton, editAction === 'exclude' && styles.chipActive]} onPress={() => setEditAction('exclude')}>
                <Text style={styles.chipText}>Private / gone</Text>
              </Pressable>
              <Pressable style={[styles.smallButton, editAction === 'undrive' && styles.chipActive]} onPress={() => setEditAction('undrive')}>
                <Text style={styles.chipText}>Un-mark</Text>
              </Pressable>
            </View>
          </View>
          <Pressable style={[styles.mainButton, styles.buttonBlue]} onPress={() => setEditMode(false)}>
            <Text style={styles.buttonText}>Done</Text>
          </Pressable>
        </View>
      ) : (
        <View style={styles.bottomBar}>
          <View style={{ flex: 1 }}>
            {countyStats ? (
              <>
                <Text style={styles.barLine}>
                  {focusRow ? `${shortCounty(focusRow.name)} ${focusRow.percent.toFixed(2)}%` : 'Ireland'}
                  <Text style={styles.barDim}>{`  ·  Ireland ${countyFigures.nationalPercent.toFixed(3)}%`}</Text>
                </Text>
              </>
            ) : (
              <Text style={styles.barDim}>Connect once to load road totals</Text>
            )}
            {tracking && (
              <Text style={styles.barLive}>
                ● {formatDuration(elapsed)} · {km(driveDistanceRef.current)} km · +{km(driveNewMRef.current)} km new
              </Text>
            )}
          </View>
          <Pressable
            style={[styles.mainButton, tracking && styles.mainButtonStop, !tracking && recheckProgress !== null && styles.mainButtonBusy]}
            onPress={tracking ? stop : start}
            disabled={!tracking && recheckProgress !== null}
          >
            <Text style={styles.buttonText}>{tracking ? 'Stop' : 'Start'}</Text>
            <Text style={styles.modeLabel}>
              {tracking
                ? activeModeRef.current === 'high' ? 'High' : activeModeRef.current === 'balanced' ? 'Balanced' : 'Saver'
                : ACCURACY_MODES.find((m) => m.key === accuracyMode)?.label}
            </Text>
          </Pressable>
        </View>
      )}

      {MAP_TYPES[mapTypeIndex] === 'osm' && (
        <View style={styles.osmCredit} pointerEvents="none">
          <Text style={styles.osmCreditText}>© OpenStreetMap contributors</Text>
        </View>
      )}
    </View>
  );
}

function StatTile({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.statTile}>
      <Text style={styles.statValue}>{value}</Text>
      <Text style={styles.statLabel}>{label}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#111' },
  map: { flex: 1 },
  onboardContainer: { flex: 1, backgroundColor: '#111', alignItems: 'center', justifyContent: 'center', padding: 24 },
  onboardTitle: { color: '#fff', fontSize: 32, fontWeight: '700', marginBottom: 20 },
  onboardText: { color: '#aaa', fontSize: 14, textAlign: 'center', marginBottom: 12 },
  onboardError: { color: '#e0a030', fontSize: 13, textAlign: 'center', marginBottom: 12 },
  countyList: { maxHeight: 320, alignSelf: 'stretch', marginTop: 8 },
  countyRow: { paddingVertical: 12, paddingHorizontal: 16, backgroundColor: '#1c1c1c', borderRadius: 8, marginBottom: 6 },
  countyRowText: { color: '#fff', fontSize: 15, textAlign: 'center' },
  skipLink: { marginTop: 16 },
  linkText: { color: '#6aa9ff', fontSize: 14 },

  topBar: { position: 'absolute', top: 56, left: 12, right: 12, flexDirection: 'row', justifyContent: 'space-between' },
  topGroup: { flexDirection: 'row', gap: 8 },
  chip: { backgroundColor: 'rgba(17,17,17,0.88)', borderRadius: 18, paddingVertical: 8, paddingHorizontal: 14 },
  chipActive: { backgroundColor: '#2f6f3a' },
  chipHeat: { backgroundColor: '#a3471a' },

  heatBar: {
    position: 'absolute',
    top: 104,
    left: 12,
    right: 12,
    backgroundColor: 'rgba(17,17,17,0.88)',
    borderRadius: 12,
    paddingVertical: 7,
    paddingHorizontal: 12,
    gap: 4,
  },
  legendRow: { flexDirection: 'row', alignItems: 'center' },
  legendStep: { flex: 1, height: 6 },
  legendText: { color: '#ccc', fontSize: 11, fontWeight: '600', marginHorizontal: 4 },
  highlightText: { flex: 1, color: '#fff', fontSize: 13, fontWeight: '600' },

  tabBar: { flexGrow: 0, marginBottom: 12 },
  tabPill: { backgroundColor: '#2a2a2a', borderRadius: 16, paddingVertical: 7, paddingHorizontal: 14 },
  tabPillActive: { backgroundColor: '#2f6f3a' },
  bigStat: { color: '#39d353', fontSize: 30, fontWeight: '800' },
  sectionTitle: { color: '#fff', fontSize: 14, fontWeight: '700', marginTop: 16, marginBottom: 6 },
  statGrid: { flexDirection: 'row', gap: 8 },
  statTile: { flex: 1, backgroundColor: '#1f1f1f', borderRadius: 10, paddingVertical: 10, paddingHorizontal: 8 },
  statValue: { color: '#fff', fontSize: 15, fontWeight: '700' },
  statLabel: { color: '#8a8a8a', fontSize: 11, marginTop: 2 },
  recordLine: { color: '#ddd', fontSize: 13, paddingVertical: 4 },
  roadRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8, paddingHorizontal: 4, borderRadius: 8 },
  roadRank: { color: '#777', fontSize: 12, width: 18, textAlign: 'right' },
  roadSwatch: { width: 10, height: 26, borderRadius: 3 },
  roadName: { color: '#fff', fontSize: 14, fontWeight: '600' },
  roadCount: { color: '#fff', fontSize: 15, fontWeight: '700' },
  patchyTag: { color: '#e8b040', fontSize: 12, fontWeight: '600' },
  modeLabel: { color: 'rgba(255,255,255,0.7)', fontSize: 10, textAlign: 'center', marginTop: 1 },
  osmCredit: { position: 'absolute', bottom: 12, left: 16, backgroundColor: 'rgba(255,255,255,0.75)', borderRadius: 4, paddingHorizontal: 5 },
  osmCreditText: { color: '#333', fontSize: 10 },
  chipText: { color: '#fff', fontSize: 13, fontWeight: '600' },

  toast: {
    position: 'absolute',
    bottom: 116,
    left: 12,
    right: 72,
    backgroundColor: 'rgba(17,17,17,0.92)',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  toastText: { color: '#e8c070', fontSize: 13 },

  panel: {
    position: 'absolute',
    top: 104,
    left: 12,
    right: 12,
    maxHeight: '58%',
    backgroundColor: 'rgba(17,17,17,0.96)',
    borderRadius: 14,
    padding: 16,
  },
  panelTitle: { color: '#fff', fontSize: 16, fontWeight: '700', marginBottom: 10 },
  small: { color: '#8a8a8a', fontSize: 12, marginTop: 8, lineHeight: 17 },
  statsHeadline: { color: '#39d353', fontSize: 14, fontWeight: '600', marginBottom: 8 },
  countyStatRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 5, paddingHorizontal: 6, borderRadius: 6 },
  countyStatRowCurrent: { backgroundColor: 'rgba(57,211,83,0.15)' },
  countyStatName: { color: '#888', fontSize: 13 },
  countyStatNameDriven: { color: '#fff', fontWeight: '600' },
  countyStatValue: { color: '#aaa', fontSize: 12 },
  driveRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 9, paddingHorizontal: 8, borderRadius: 8 },
  driveRowSelected: { backgroundColor: 'rgba(255,159,26,0.15)' },
  driveWhen: { color: '#fff', fontSize: 14, fontWeight: '600' },
  driveInfo: { color: '#9a9a9a', fontSize: 12, marginTop: 2 },
  logText: { color: '#7fd67f', fontSize: 10, fontFamily: 'Courier' },

  row: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginTop: 8 },
  button: { flexGrow: 1, paddingVertical: 11, paddingHorizontal: 14, borderRadius: 10, alignItems: 'center' },
  buttonText: { color: '#fff', fontSize: 14, fontWeight: '600', textAlign: 'center' },
  buttonBlue: { backgroundColor: '#2a4f8a' },
  buttonPurple: { backgroundColor: '#5a3a8a' },
  buttonGrey: { backgroundColor: '#333' },
  buttonOn: { backgroundColor: '#3a6fb0' },
  buttonRed: { backgroundColor: '#5a2a2a' },
  buttonRedConfirm: { backgroundColor: '#a03030' },
  smallButton: { backgroundColor: '#333', borderRadius: 8, paddingVertical: 7, paddingHorizontal: 12 },
  smallButtonDanger: { backgroundColor: '#a03030' },

  recentreButton: {
    position: 'absolute',
    bottom: 124,
    right: 16,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(17,17,17,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recentreText: { color: '#6aa9ff', fontSize: 24, fontWeight: '700' },

  bottomBar: {
    position: 'absolute',
    bottom: 34,
    left: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(17,17,17,0.9)',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  barLine: { color: '#fff', fontSize: 15, fontWeight: '600' },
  barDim: { color: '#9a9a9a', fontSize: 13, fontWeight: '400' },
  barLive: { color: '#ff7a7a', fontSize: 13, marginTop: 4 },
  mainButton: { backgroundColor: '#2a6f2a', paddingVertical: 14, paddingHorizontal: 26, borderRadius: 12 },
  mainButtonStop: { backgroundColor: '#8a2a2a' },
  mainButtonBusy: { opacity: 0.4 },
});
