import { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import { StyleSheet, Text, View, Pressable, ScrollView, ActivityIndicator, Dimensions } from 'react-native';
import MapView, { Polyline, LocalTile, PROVIDER_DEFAULT, MapPressEvent, MapType, Region } from 'react-native-maps';
import * as Location from 'expo-location';
import * as TaskManager from 'expo-task-manager';
import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as DocumentPicker from 'expo-document-picker';
import * as store from './src/storage';
import { RoadNetwork, RoadSegment, parseChunkId } from './src/roadMatcher';
import { DriveMatcher, Point } from './src/coverage';
import { recheckDrives } from './src/recheck';
import { Coord, lineLengthMeters, distanceMeters, tileIdForPoint, neighbourTileIds } from './src/geo';
import { DrivenTileRenderer } from './src/tileRenderer';

// Every road tile is fetched live from the public repo over GitHub's raw
// file CDN. Tile ids must match scripts/tile-county.js (see src/geo.ts).
const TILES_BASE_URL = 'https://raw.githubusercontent.com/0204Killian/tarmacked/main/tiles/';
const LOCATION_TASK_NAME = 'tarmacked-background-location';

// Edit mode only draws roads once zoomed in this far (a few km across).
const EDIT_MAX_LAT_DELTA = 0.06;
// A pause longer than this inside one old recording = two separate drives.
const DRIVE_SPLIT_GAP_MS = 15 * 60 * 1000;
const NOTE_MS = 7000;
const LOG_LINES = 60;

// Real road totals for every county and the whole Republic, generated by
// scripts/tile-county.js alongside the tiles. Cached for offline use.
type CountyStats = { counties: string[]; totalMeters: number[]; nationalMeters: number };
type RenderMode = 'images' | 'lines';
type Panel = null | 'stats' | 'drives' | 'dev';
type Chain = { coords: Coord[]; minLat: number; maxLat: number; minLon: number; maxLon: number };

const shortCounty = (name: string) => name.replace(/^County /, '');
const MAP_TYPES: MapType[] = ['standard', 'satellite', 'hybrid'];
const FALLBACK_REGION = { latitude: 53.1, longitude: -7.7, latitudeDelta: 4, longitudeDelta: 4 };
const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

const pad2 = (n: number) => String(n).padStart(2, '0');
function formatWhen(t: number) {
  const d = new Date(t);
  return `${DAYS[d.getDay()]} ${d.getDate()} ${MONTHS[d.getMonth()]} · ${pad2(d.getHours())}:${pad2(d.getMinutes())}`;
}
function formatDuration(ms: number) {
  const min = Math.max(0, Math.round(ms / 60000));
  return min < 60 ? `${min} min` : `${Math.floor(min / 60)}h ${pad2(min % 60)}m`;
}
const km = (m: number, dp = 1) => (m / 1000).toFixed(dp);
const toLatLng = (c: Coord[]) => c.map(([latitude, longitude]) => ({ latitude, longitude }));

// Joins driven chunks of the same road into continuous lines, so the map
// draws a few long lines instead of thousands of 100m pieces.
function buildChains(ids: Iterable<string>, shapeOf: (id: string) => Coord[] | undefined): Chain[] {
  const byWay = new Map<string, { idx: number; coords: Coord[] }[]>();
  const loose: Coord[][] = [];
  for (const id of ids) {
    const coords = shapeOf(id);
    if (!coords || coords.length < 2) continue;
    const p = parseChunkId(id);
    if (!p) {
      loose.push(coords);
      continue;
    }
    const list = byWay.get(p.way);
    if (list) list.push({ idx: p.idx, coords });
    else byWay.set(p.way, [{ idx: p.idx, coords }]);
  }
  const lines: Coord[][] = [...loose];
  byWay.forEach((parts) => {
    parts.sort((a, b) => a.idx - b.idx);
    let cur = parts[0].coords.slice();
    for (let i = 1; i < parts.length; i++) {
      const prevEnd = cur[cur.length - 1];
      const next = parts[i].coords;
      if (parts[i].idx === parts[i - 1].idx + 1 && prevEnd[0] === next[0][0] && prevEnd[1] === next[0][1]) {
        cur.push(...next.slice(1));
      } else {
        lines.push(cur);
        cur = next.slice();
      }
    }
    lines.push(cur);
  });
  return lines.map((coords) => {
    let minLat = Infinity, maxLat = -Infinity, minLon = Infinity, maxLon = -Infinity;
    for (const [la, lo] of coords) {
      if (la < minLat) minLat = la;
      if (la > maxLat) maxLat = la;
      if (lo < minLon) minLon = lo;
      if (lo > maxLon) maxLon = lo;
    }
    return { coords, minLat, maxLat, minLon, maxLon };
  });
}

// --- Background location: points land here and are picked up every 2s ---
let recordedPoints: Point[] = [];

TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }) => {
  if (error) {
    console.error(error);
    return;
  }
  if (data) {
    const { locations } = data as { locations: Location.LocationObject[] };
    for (const loc of locations) {
      recordedPoints.push({ latitude: loc.coords.latitude, longitude: loc.coords.longitude, timestamp: loc.timestamp });
    }
  }
});

function withTimeout<T>(promise: Promise<T>, ms: number, label: string): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>((_, reject) => setTimeout(() => reject(new Error(`${label} timed out after ${ms / 1000}s`)), ms)),
  ]);
}

export default function App() {
  // null = still loading; false = needs onboarding; true = ready
  const [onboarded, setOnboarded] = useState<boolean | null>(null);
  const [onboardingCounties, setOnboardingCounties] = useState<string[] | null>(null);
  const [onboardingError, setOnboardingError] = useState('');
  const [downloadingCounty, setDownloadingCounty] = useState<string | null>(null);
  const [downloadProgress, setDownloadProgress] = useState({ done: 0, total: 0 });
  const [homeCounty, setHomeCounty] = useState<string | null>(null);

  const [tracking, setTracking] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [editAction, setEditAction] = useState<'exclude' | 'undrive'>('exclude');
  const [following, setFollowing] = useState(true);
  const [panel, setPanel] = useState<Panel>(null);
  const [mapTypeIndex, setMapTypeIndex] = useState(0);
  const [region, setRegion] = useState(FALLBACK_REGION);
  const [visibleRegion, setVisibleRegion] = useState<Region>(FALLBACK_REGION);
  const mapRef = useRef<MapView | null>(null);

  // Driven / excluded roads. The refs are the source of truth (read inside
  // timers and async work); the state copies make the screen update.
  const drivenRef = useRef<Set<string>>(new Set());
  const excludedRef = useRef<Set<string>>(new Set());
  const [drivenIds, setDrivenIds] = useState<Set<string>>(new Set());
  const [excludedIds, setExcludedIds] = useState<Set<string>>(new Set());
  // Stored with each driven road so it draws and counts even when the road
  // data for that area isn't downloaded.
  const drivenShapesRef = useRef<Map<string, Coord[]>>(new Map());
  const drivenCountyRef = useRef<Map<string, number>>(new Map());
  const lengthRef = useRef<Map<string, number>>(new Map());
  const excludedInfoRef = useRef<Map<string, { c: number | null; l: number | null }>>(new Map());
  const unmarkedRef = useRef<Map<string, number>>(new Map());

  // Downloaded road data.
  const netRef = useRef(new RoadNetwork());
  const knownTilesRef = useRef<Set<string>>(new Set());
  const [netRev, setNetRev] = useState(0);

  const [countyStats, setCountyStats] = useState<CountyStats | null>(null);
  const [currentCounty, setCurrentCounty] = useState<number | null>(null);

  // The drive in progress.
  const matcherRef = useRef<DriveMatcher | null>(null);
  const currentDriveIdRef = useRef<number | null>(null);
  const driveStartRef = useRef(0);
  const driveDistanceRef = useRef(0);
  const driveNewMRef = useRef(0);
  const lastLivePointRef = useRef<Point | null>(null);
  const processedIndexRef = useRef(0);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const foregroundSub = useRef<Location.LocationSubscription | null>(null);
  const [liveIds, setLiveIds] = useState<string[]>([]);
  const [liveTrail, setLiveTrail] = useState<Point[]>([]);

  // Drives list / drive shown on the map.
  const [drives, setDrives] = useState<store.DriveSummary[] | null>(null);
  const [selectedDrive, setSelectedDrive] = useState<{ id: number; points: Point[] } | null>(null);
  const [deleteConfirmId, setDeleteConfirmId] = useState<number | null>(null);

  // Dev / housekeeping.
  const [unmatchedCount, setUnmatchedCount] = useState(0);
  const [rawStats, setRawStats] = useState({ drives: 0, points: 0 });
  const [rawSessions, setRawSessions] = useState<Point[][] | null>(null);
  const [recheckProgress, setRecheckProgress] = useState<number | null>(null);
  const [removedCount, setRemovedCount] = useState(0);
  const [simulateTaps, setSimulateTaps] = useState(false);
  const [confirming, setConfirming] = useState<null | 'reset' | 'uninstall'>(null);
  const [backupBusy, setBackupBusy] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [note, setNoteText] = useState('');
  const noteTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [log, setLog] = useState<string[]>([]);

  // Map drawing.
  const rendererRef = useRef<DrivenTileRenderer | null>(null);
  const [renderMode, setRenderMode] = useState<RenderMode>('images');
  const [tileKey, setTileKey] = useState(0);
  const [dataLoaded, setDataLoaded] = useState(false);

  const setNote = useCallback((text: string) => {
    setNoteText(text);
    if (noteTimer.current) clearTimeout(noteTimer.current);
    if (text) noteTimer.current = setTimeout(() => setNoteText(''), NOTE_MS);
  }, []);
  const addLog = useCallback((line: string) => {
    const d = new Date();
    setLog((prev) => [...prev.slice(-(LOG_LINES - 1)), `${pad2(d.getHours())}:${pad2(d.getMinutes())} ${line}`]);
  }, []);

  // ---------- Driven-road bookkeeping ----------

  const rememberDriven = (id: string, shape: Coord[] | null, county: number | null) => {
    if (shape) {
      drivenShapesRef.current.set(id, shape);
      lengthRef.current.set(id, lineLengthMeters(shape));
    }
    if (county !== null) drivenCountyRef.current.set(id, county);
  };

  const forgetDriven = (id: string) => {
    drivenShapesRef.current.delete(id);
    drivenCountyRef.current.delete(id);
    lengthRef.current.delete(id);
  };

  // Marks roads as driven. Returns the ones that weren't driven before.
  const markDriven = (ids: string[]): string[] => {
    const net = netRef.current;
    const fresh = ids.filter((id) => !drivenRef.current.has(id) && !excludedRef.current.has(id));
    if (fresh.length === 0) return [];
    const rows = fresh.map((id) => {
      const seg = net.segs.get(id);
      const shape = drivenShapesRef.current.get(id) ?? seg?.coords ?? null;
      const county = drivenCountyRef.current.get(id) ?? seg?.c ?? null;
      rememberDriven(id, shape, county);
      drivenRef.current.add(id);
      return { id, shape, county };
    });
    setDrivenIds(new Set(drivenRef.current));
    store.addDriven(rows).catch((e) => setNote(`Couldn't save driven roads: ${(e as Error).message}`));
    return fresh;
  };

  // When road data arrives, fill in shape/county/length for driven or
  // excluded roads we didn't know them for (e.g. older history).
  const backfillFromSegments = (segs: RoadSegment[]) => {
    const drivenFill: { id: string; shape: Coord[]; county: number | null }[] = [];
    const excludedFill: { id: string; county: number | null; lengthM: number }[] = [];
    for (const seg of segs) {
      if (drivenRef.current.has(seg.id)) {
        const needShape = !drivenShapesRef.current.has(seg.id);
        const needCounty = seg.c !== undefined && !drivenCountyRef.current.has(seg.id);
        if (needShape || needCounty) {
          const shape = drivenShapesRef.current.get(seg.id) ?? seg.coords;
          rememberDriven(seg.id, shape, seg.c ?? null);
          drivenFill.push({ id: seg.id, shape, county: seg.c ?? null });
        }
      }
      const ex = excludedInfoRef.current.get(seg.id);
      if (ex && (ex.c === null || ex.l === null)) {
        const next = { c: ex.c ?? seg.c ?? null, l: ex.l ?? lineLengthMeters(seg.coords) };
        excludedInfoRef.current.set(seg.id, next);
        excludedFill.push({ id: seg.id, county: next.c, lengthM: next.l });
      }
    }
    if (drivenFill.length > 0) store.addDriven(drivenFill).catch(() => undefined);
    if (excludedFill.length > 0) store.fillExcludedInfo(excludedFill).catch(() => undefined);
    return drivenFill.length;
  };

  const addRoadData = (segs: RoadSegment[]) => {
    if (segs.length === 0) return;
    netRef.current.add(segs);
    const filled = backfillFromSegments(segs);
    setNetRev((r) => r + 1);
    if (filled > 0) setDrivenIds(new Set(drivenRef.current)); // stats may change
  };

  // ---------- Road data tiles ----------

  // 'ok' = downloaded (or nothing there), 'fail' = network problem.
  const fetchTile = async (tileId: string): Promise<'ok' | 'fail'> => {
    if (knownTilesRef.current.has(tileId)) return 'ok';
    knownTilesRef.current.add(tileId); // mark in-flight so bursts don't duplicate
    try {
      const res = await fetch(`${TILES_BASE_URL}${tileId}.json`);
      if (!res.ok) return 'ok'; // not tiled (sea, outside Ireland)
      const data = await res.json();
      const segs: RoadSegment[] = data.segments || [];
      if (segs.length > 0) {
        addRoadData(segs);
        addLog(`road data: ${tileId} (${segs.length})`);
        store.putTiles([{ tileId, segments: segs }], false).catch(() => undefined);
      }
      return 'ok';
    } catch {
      knownTilesRef.current.delete(tileId); // retry later
      return 'fail';
    }
  };

  // Downloads any of these tiles we don't have. Returns how many failed.
  const ensureTiles = async (tileIds: Iterable<string>, onProgress?: (f: number) => void) => {
    const missing = Array.from(new Set(tileIds)).filter((t) => !knownTilesRef.current.has(t));
    let failed = 0;
    for (let i = 0; i < missing.length; i += 8) {
      const results = await Promise.all(missing.slice(i, i + 8).map(fetchTile));
      failed += results.filter((r) => r === 'fail').length;
      onProgress?.(Math.min(1, (i + 8) / missing.length));
    }
    return failed;
  };

  const downloadHomeCounty = async (county: string) => {
    setDownloadingCounty(county);
    setOnboardingError('');
    try {
      const indexRes = await fetch(`${TILES_BASE_URL}county-index.json`);
      const index = await indexRes.json();
      const tileIds: string[] = index[county] || [];
      setDownloadProgress({ done: 0, total: tileIds.length });
      const entries: store.TileEntry[] = [];
      for (let i = 0; i < tileIds.length; i += 8) {
        const results = await Promise.all(
          tileIds.slice(i, i + 8).map(async (tileId) => {
            try {
              const res = await fetch(`${TILES_BASE_URL}${tileId}.json`);
              if (!res.ok) return { tileId, segments: [] as RoadSegment[] };
              const data = await res.json();
              return { tileId, segments: (data.segments || []) as RoadSegment[] };
            } catch {
              return { tileId, segments: [] as RoadSegment[] };
            }
          })
        );
        for (const r of results) {
          if (r.segments.length > 0) entries.push(r);
          knownTilesRef.current.add(r.tileId);
        }
        setDownloadProgress({ done: Math.min(i + 8, tileIds.length), total: tileIds.length });
      }
      addRoadData(entries.flatMap((e) => e.segments));
      await store.putTiles(entries, true); // home county is never auto-cleared
      await store.setMeta('home_county', county);
      await store.setMeta('onboarded', 'true');
      setHomeCounty(county);
      setOnboarded(true);
      return true;
    } catch (e) {
      setOnboardingError(`Download failed: ${(e as Error).message}. Check your connection and try again.`);
      return false;
    } finally {
      setDownloadingCounty(null);
    }
  };

  const skipOnboarding = async () => {
    await store.setMeta('onboarded', 'true');
    setOnboarded(true);
  };

  // ---------- Loading ----------

  useEffect(() => {
    (async () => {
      try {
        const migrated = await store.migrateIfNeeded();
        if (migrated) setNote(migrated);
      } catch (e) {
        setNote(`Couldn't move your data to the new storage yet (${(e as Error).message}). Nothing was deleted — it retries next launch.`);
      }
      try {
        await store.evictStaleTiles();
        const data = await store.loadAll();
        for (const d of data.driven) {
          drivenRef.current.add(d.id);
          rememberDriven(d.id, d.shape, d.county);
        }
        for (const e of data.excluded) {
          excludedRef.current.add(e.id);
          excludedInfoRef.current.set(e.id, { c: e.county, l: e.lengthM });
        }
        unmarkedRef.current = await store.loadUnmarked();
        const segs = data.tiles.flatMap((t) => t.segments);
        data.tiles.forEach((t) => knownTilesRef.current.add(t.tileId));
        addRoadData(segs);
        setDrivenIds(new Set(drivenRef.current));
        setExcludedIds(new Set(excludedRef.current));
        setUnmatchedCount(data.unmatched.length);
        setRawStats({ drives: data.driveCount, points: data.pointCount });
        setRemovedCount(await store.countRemoved());
        const mode = await store.getMeta('render_mode');
        if (mode === 'lines' || mode === 'images') setRenderMode(mode);
        if (data.homeCounty) setHomeCounty(data.homeCounty);
        setOnboarded(data.onboarded);
        setDataLoaded(true);
      } catch (e) {
        setNote(`Couldn't load saved data: ${(e as Error).message}`);
        setOnboarded(false);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // County totals: cached copy straight away, then a fresh one from GitHub.
  useEffect(() => {
    (async () => {
      try {
        const cached = await store.getMeta('county_stats');
        if (cached) setCountyStats(JSON.parse(cached));
      } catch {
        // no cached copy yet
      }
      try {
        const res = await fetch(`${TILES_BASE_URL}county-stats.json`);
        if (!res.ok) return;
        const fresh = await res.json();
        if (!Array.isArray(fresh.counties) || !Array.isArray(fresh.totalMeters)) return;
        setCountyStats(fresh);
        await store.setMeta('county_stats', JSON.stringify(fresh));
      } catch {
        // offline — the cached copy (if any) stays in use
      }
    })();
  }, []);

  useEffect(() => {
    if (onboarded !== false || onboardingCounties !== null) return;
    (async () => {
      try {
        const res = await fetch(`${TILES_BASE_URL}county-index.json`);
        if (!res.ok) throw new Error(`index responded ${res.status}`);
        const index = await res.json();
        setOnboardingCounties(Object.keys(index).sort());
      } catch (e) {
        setOnboardingError(`Couldn't reach GitHub to list counties (${(e as Error).message}). Check your connection and try again.`);
      }
    })();
  }, [onboarded, onboardingCounties]);

  // Location permissions and a first fix to centre the map.
  useEffect(() => {
    if (onboarded !== true) return;
    (async () => {
      try {
        const fg = await withTimeout(Location.requestForegroundPermissionsAsync(), 8000, 'foreground permission');
        addLog(`location permission: ${fg.status}`);
      } catch (e) {
        addLog(`location permission failed: ${(e as Error).message}`);
      }
      try {
        const bg = await withTimeout(Location.requestBackgroundPermissionsAsync(), 8000, 'background permission');
        addLog(`background permission: ${bg.status}`);
      } catch (e) {
        addLog(`background permission failed: ${(e as Error).message}`);
      }
      try {
        const current = await withTimeout(Location.getCurrentPositionAsync({}), 8000, 'get current position');
        const here = { latitude: current.coords.latitude, longitude: current.coords.longitude, latitudeDelta: 0.05, longitudeDelta: 0.05 };
        setRegion(here);
        setVisibleRegion(here);
        mapRef.current?.animateToRegion(here, 300);
      } catch (e) {
        addLog(`no position yet: ${(e as Error).message}`);
      }
    })();
  }, [onboarded, addLog]);

  // ---------- Re-checking drives ----------

  const recheckRunning = useRef(false);

  /**
   * Replays every saved drive through the matching rules and updates which
   * roads count as driven (adding and removing). Downloads road data for
   * everywhere you've driven first; if that isn't possible (no signal) it
   * does nothing and tries again later. Removed roads can be put back.
   */
  const runRecheck = async (reason: 'upgrade' | 'manual' | 'deleted'): Promise<boolean> => {
    if (recheckRunning.current) return false;
    recheckRunning.current = true;
    setRecheckProgress(0);
    try {
      const allDrives = await store.loadDrives();
      const tiles = new Set<string>();
      const visited = new Set<string>();
      for (const d of allDrives) {
        for (const p of d.points) {
          const own = tileIdForPoint(p.latitude, p.longitude);
          if (visited.has(own)) continue;
          visited.add(own);
          neighbourTileIds(p.latitude, p.longitude).forEach((t) => tiles.add(t));
        }
      }
      // Also the road data for driven roads we have no county for yet.
      drivenRef.current.forEach((id) => {
        if (drivenCountyRef.current.has(id)) return;
        const shape = drivenShapesRef.current.get(id);
        if (shape) tiles.add(tileIdForPoint(shape[0][0], shape[0][1]));
      });
      const failed = await ensureTiles(tiles, (f) => setRecheckProgress(f * 0.3));
      if (failed > 0) {
        await store.setMeta('recheck_pending', '1');
        setNote(`Couldn't download road data for ${failed} area(s) — I'll re-check your drives next time you have signal.`);
        return false;
      }
      const current = new Map<string, Coord[] | null>();
      drivenRef.current.forEach((id) => current.set(id, drivenShapesRef.current.get(id) ?? null));
      const result = await recheckDrives(
        netRef.current,
        allDrives,
        current,
        excludedRef.current,
        unmarkedRef.current,
        (f) => setRecheckProgress(0.3 + f * 0.7)
      );
      const net = netRef.current;
      const addRows = result.add.map((id) => {
        const seg = net.segs.get(id);
        return { id, shape: seg?.coords ?? null, county: seg?.c ?? null };
      });
      await store.applyRecheck(addRows, result.remove);
      await store.setDriveStats(result.stats);
      await store.replaceUnmatched(result.unmatched);
      await store.setMeta('recheck_pending', '');
      for (const r of addRows) {
        drivenRef.current.add(r.id);
        rememberDriven(r.id, r.shape, r.county);
      }
      for (const id of result.remove) {
        drivenRef.current.delete(id);
        forgetDriven(id);
      }
      setDrivenIds(new Set(drivenRef.current));
      setUnmatchedCount(result.unmatched.length);
      setRemovedCount(await store.countRemoved());
      setRawStats({ drives: allDrives.length, points: allDrives.reduce((n, d) => n + d.points.length, 0) });
      if (drives !== null) setDrives(await store.listDrives());
      const changed = result.add.length + result.remove.length;
      if (reason !== 'deleted' || changed > 0) {
        setNote(
          `Re-checked ${allDrives.length} drive(s): ${result.add.length} road pieces added, ${result.remove.length} removed.` +
            (result.remove.length > 0 ? ' Removed ones can be put back from Dev.' : '')
        );
      }
      addLog(`re-check (${reason}): +${result.add.length} −${result.remove.length}`);
      return true;
    } catch (e) {
      setNote(`Re-check failed: ${(e as Error).message}. Nothing was changed.`);
      return false;
    } finally {
      recheckRunning.current = false;
      setRecheckProgress(null);
    }
  };

  // First launch of v0.13: split old recordings into drives and re-check
  // everything with the new rule. Also retries a re-check that couldn't run.
  useEffect(() => {
    if (!dataLoaded || onboarded !== true) return;
    (async () => {
      const upgraded = await store.getMeta('v013_upgrade');
      const pending = await store.getMeta('recheck_pending');
      if (!upgraded) {
        const { split, dropped } = await store.splitDrivesOnGaps(DRIVE_SPLIT_GAP_MS);
        addLog(`drives tidied: ${split} split, ${dropped} empty removed`);
        await store.setMeta('v013_split', '1');
        if (await runRecheck('upgrade')) await store.setMeta('v013_upgrade', String(Date.now()));
      } else if (pending === '1') {
        await runRecheck('manual');
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dataLoaded, onboarded]);

  // ---------- Tracking ----------

  const processPoints = (newPoints: Point[]) => {
    if (newPoints.length === 0) return;
    // Fetch road data around you before you need it.
    const wanted = new Set<string>();
    for (const p of newPoints) neighbourTileIds(p.latitude, p.longitude).forEach((t) => wanted.add(t));
    wanted.forEach((t) => {
      if (!knownTilesRef.current.has(t)) fetchTile(t);
    });

    const matcher = matcherRef.current;
    if (matcher) {
      const result = matcher.feed(newPoints);
      const fresh = markDriven(result.completed);
      if (fresh.length > 0) {
        driveNewMRef.current += fresh.reduce((m, id) => m + (lengthRef.current.get(id) ?? 0), 0);
        setLiveIds((prev) => [...prev, ...fresh]);
      }
      if (result.unmatched.length > 0) {
        setUnmatchedCount((n) => n + result.unmatched.length);
        store.addUnmatched(result.unmatched).catch(() => undefined);
      }
      const last = matcher.lastChunkId ? netRef.current.segs.get(matcher.lastChunkId) : undefined;
      if (last?.c !== undefined) setCurrentCounty(last.c);
    }

    for (const p of newPoints) {
      const prev = lastLivePointRef.current;
      if (prev && p.timestamp - prev.timestamp <= 60_000) driveDistanceRef.current += distanceMeters(prev, p);
      lastLivePointRef.current = p;
    }
    const driveId = currentDriveIdRef.current;
    if (driveId !== null) {
      store.addPoints(driveId, newPoints).catch((e) => setNote(`Couldn't save GPS points: ${(e as Error).message}`));
    }
    setRawStats((prev) => ({ ...prev, points: prev.points + newPoints.length }));
    setLiveTrail((prev) => [...prev, ...newPoints]);
    store.touchTiles(Array.from(new Set(newPoints.map((p) => tileIdForPoint(p.latitude, p.longitude))))).catch(() => undefined);
  };

  const processRef = useRef(processPoints);
  processRef.current = processPoints;

  useEffect(() => {
    if (!tracking) return;
    pollRef.current = setInterval(() => {
      const newPoints = recordedPoints.slice(processedIndexRef.current);
      processedIndexRef.current = recordedPoints.length;
      processRef.current(newPoints);
    }, 2000);
    return () => {
      if (pollRef.current) clearInterval(pollRef.current);
    };
  }, [tracking]);

  const start = async () => {
    recordedPoints = [];
    processedIndexRef.current = 0;
    matcherRef.current = new DriveMatcher(netRef.current, excludedRef.current);
    driveStartRef.current = Date.now();
    driveDistanceRef.current = 0;
    driveNewMRef.current = 0;
    lastLivePointRef.current = null;
    setLiveIds([]);
    setLiveTrail([]);
    setSelectedDrive(null);
    setPanel(null);
    setFollowing(true);
    try {
      currentDriveIdRef.current = await store.startDrive(driveStartRef.current);
      setRawStats((prev) => ({ ...prev, drives: prev.drives + 1 }));
    } catch (e) {
      currentDriveIdRef.current = null;
      setNote(`Couldn't start saving this drive (${(e as Error).message}) — roads will still be matched.`);
    }
    try {
      await withTimeout(
        Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
          accuracy: Location.Accuracy.BestForNavigation,
          timeInterval: 2000,
          distanceInterval: 10,
          activityType: Location.ActivityType.AutomotiveNavigation,
          pausesUpdatesAutomatically: false,
          showsBackgroundLocationIndicator: true,
          foregroundService: { notificationTitle: 'tarmacked is tracking', notificationBody: 'Recording this drive' },
        }),
        8000,
        'start background tracking'
      );
    } catch (e) {
      addLog(`background tracking unavailable: ${(e as Error).message}`);
      try {
        foregroundSub.current = await Location.watchPositionAsync(
          { accuracy: Location.Accuracy.BestForNavigation, timeInterval: 2000, distanceInterval: 10 },
          (loc) => {
            recordedPoints.push({ latitude: loc.coords.latitude, longitude: loc.coords.longitude, timestamp: loc.timestamp });
          }
        );
        setNote('Tracking only while the app is open (background location unavailable).');
      } catch {
        setNote('No GPS available.');
      }
    }
    setTracking(true);
  };

  const stop = async () => {
    try {
      await Location.stopLocationUpdatesAsync(LOCATION_TASK_NAME);
    } catch {
      // wasn't running as a background task
    }
    if (foregroundSub.current) {
      foregroundSub.current.remove();
      foregroundSub.current = null;
    }
    const newPoints = recordedPoints.slice(processedIndexRef.current);
    processedIndexRef.current = recordedPoints.length;
    processPoints(newPoints);
    const matcher = matcherRef.current;
    if (matcher) {
      const fresh = markDriven(matcher.finish());
      driveNewMRef.current += fresh.reduce((m, id) => m + (lengthRef.current.get(id) ?? 0), 0);
    }
    matcherRef.current = null;
    const driveId = currentDriveIdRef.current;
    if (driveId !== null) {
      if (recordedPoints.length < 2) {
        store.deleteDrive(driveId).catch(() => undefined); // nothing recorded
        setRawStats((prev) => ({ ...prev, drives: Math.max(0, prev.drives - 1) }));
      } else {
        store
          .setDriveStats([{ id: driveId, endedAt: Date.now(), distanceM: driveDistanceRef.current, newM: driveNewMRef.current }])
          .catch(() => undefined);
        setNote(`Drive saved: ${km(driveDistanceRef.current)} km, ${km(driveNewMRef.current)} km of new road.`);
      }
    }
    currentDriveIdRef.current = null;
    setTracking(false);
    setLiveIds([]);
    setLiveTrail([]);
    if (drives !== null) store.listDrives().then(setDrives).catch(() => undefined);
  };

  const onMapPress = (e: MapPressEvent) => {
    if (!tracking || editMode || !simulateTaps) return;
    const { latitude, longitude } = e.nativeEvent.coordinate;
    recordedPoints.push({ latitude, longitude, timestamp: Date.now() });
  };

  // ---------- Editing ----------

  const handleEditTap = (id: string) => {
    if (editAction === 'undrive') {
      if (!drivenRef.current.has(id)) return;
      drivenRef.current.delete(id);
      forgetDriven(id);
      unmarkedRef.current.set(id, Date.now());
      setDrivenIds(new Set(drivenRef.current));
      store.removeDriven(id).catch((e) => setNote(`Couldn't save that change: ${(e as Error).message}`));
      store.markUnmarked(id).catch(() => undefined);
      return;
    }
    const nowExcluded = !excludedRef.current.has(id);
    const seg = netRef.current.segs.get(id);
    const info = { c: seg?.c ?? null, l: seg ? lineLengthMeters(seg.coords) : null };
    if (nowExcluded) {
      excludedRef.current.add(id);
      excludedInfoRef.current.set(id, info);
    } else {
      excludedRef.current.delete(id);
      excludedInfoRef.current.delete(id);
    }
    setExcludedIds(new Set(excludedRef.current));
    store.setExcluded(id, nowExcluded, info.c, info.l).catch((e) => setNote(`Couldn't save that change: ${(e as Error).message}`));
  };

  // ---------- Map helpers ----------

  const recentre = async () => {
    setFollowing(true);
    try {
      const pos =
        (await Location.getLastKnownPositionAsync()) ??
        (await withTimeout(Location.getCurrentPositionAsync({}), 8000, 'get current position'));
      mapRef.current?.animateCamera({ center: { latitude: pos.coords.latitude, longitude: pos.coords.longitude } }, { duration: 400 });
    } catch {
      // no fix right now — following snaps to you on the next update anyway
    }
  };

  // ---------- Drives ----------

  const openDrives = async () => {
    setPanel((p) => (p === 'drives' ? null : 'drives'));
    try {
      setDrives(await store.listDrives());
    } catch (e) {
      setNote(`Couldn't load drives: ${(e as Error).message}`);
    }
  };

  const showDrive = async (id: number) => {
    setDeleteConfirmId(null);
    if (selectedDrive?.id === id) {
      setSelectedDrive(null);
      return;
    }
    try {
      const points = await store.loadDrivePoints(id);
      setSelectedDrive({ id, points });
      if (points.length > 1) {
        setFollowing(false);
        mapRef.current?.fitToCoordinates(
          points.map((p) => ({ latitude: p.latitude, longitude: p.longitude })),
          { edgePadding: { top: 120, right: 40, bottom: 320, left: 40 }, animated: true }
        );
      }
    } catch (e) {
      setNote(`Couldn't load that drive: ${(e as Error).message}`);
    }
  };

  const deleteDrive = async (id: number) => {
    if (deleteConfirmId !== id) {
      setDeleteConfirmId(id);
      return;
    }
    setDeleteConfirmId(null);
    if (selectedDrive?.id === id) setSelectedDrive(null);
    try {
      await store.deleteDrive(id);
      setDrives(await store.listDrives());
      const ok = await runRecheck('deleted');
      if (!ok) setNote('Drive deleted. Its roads will be re-checked once road data can be downloaded.');
    } catch (e) {
      setNote(`Couldn't delete that drive: ${(e as Error).message}`);
    }
  };

  // ---------- Dev tools ----------

  const toggleRawTrail = async () => {
    if (rawSessions) {
      setRawSessions(null);
      return;
    }
    try {
      setRawSessions((await store.loadDrives()).map((d) => d.points));
    } catch (e) {
      setNote(`Couldn't load the saved trail: ${(e as Error).message}`);
    }
  };

  const undoRecheck = async () => {
    try {
      const n = await store.restoreRemoved();
      const data = await store.loadAll();
      for (const d of data.driven) {
        if (!drivenRef.current.has(d.id)) {
          drivenRef.current.add(d.id);
          rememberDriven(d.id, d.shape, d.county);
          unmarkedRef.current.delete(d.id);
        }
      }
      setDrivenIds(new Set(drivenRef.current));
      setRemovedCount(0);
      setNote(`Put back ${n} road pieces.`);
    } catch (e) {
      setNote(`Couldn't put them back: ${(e as Error).message}`);
    }
  };

  const toggleRenderMode = () => {
    const next: RenderMode = renderMode === 'images' ? 'lines' : 'images';
    setRenderMode(next);
    store.setMeta('render_mode', next).catch(() => undefined);
  };

  // Swaps cached road data for fresh data (after the tiles are regenerated).
  const refreshRoadData = async () => {
    if (refreshing) return;
    setRefreshing(true);
    setPanel(null);
    netRef.current.clear();
    knownTilesRef.current.clear();
    setNetRev((r) => r + 1);
    try {
      await store.clearTiles();
      if (homeCounty) {
        setNote(`Refreshing road data for ${homeCounty}…`);
        const ok = await downloadHomeCounty(homeCounty);
        setNote(ok ? 'Road data refreshed. Other areas re-download as you drive.' : 'Refresh failed — check your connection.');
      } else {
        setNote('Road data cleared. Areas re-download as you drive.');
      }
    } finally {
      setRefreshing(false);
    }
  };

  const confirmThen = (what: 'reset' | 'uninstall', action: () => void) => {
    if (confirming !== what) {
      setConfirming(what);
      setTimeout(() => setConfirming((c) => (c === what ? null : c)), 4000);
      return;
    }
    setConfirming(null);
    action();
  };

  const uninstallAreas = () => {
    netRef.current.clear();
    knownTilesRef.current.clear();
    setNetRev((r) => r + 1);
    store.clearTiles().catch(() => undefined);
    setPanel(null);
  };

  const resetMap = () => {
    drivenRef.current = new Set();
    excludedRef.current = new Set();
    drivenShapesRef.current = new Map();
    drivenCountyRef.current = new Map();
    lengthRef.current = new Map();
    excludedInfoRef.current = new Map();
    unmarkedRef.current = new Map();
    setDrivenIds(new Set());
    setExcludedIds(new Set());
    setUnmatchedCount(0);
    setRawSessions(null);
    setRawStats({ drives: 0, points: 0 });
    setRemovedCount(0);
    setSelectedDrive(null);
    setDrives([]);
    store.resetProgress().catch((e) => setNote(`Reset failed: ${(e as Error).message}`));
    setPanel(null);
  };

  // ---------- Backup & restore ----------

  const exportBackup = async () => {
    if (backupBusy) return;
    setBackupBusy(true);
    try {
      const data = await store.exportBackup();
      const file = new File(Paths.cache, `tarmacked-backup-${new Date().toISOString().slice(0, 10)}.json`);
      if (file.exists) file.delete();
      file.create();
      file.write(JSON.stringify(data));
      if (!(await Sharing.isAvailableAsync())) throw new Error('sharing is not available on this device');
      await Sharing.shareAsync(file.uri, { mimeType: 'application/json', UTI: 'public.json', dialogTitle: 'Save your tarmacked backup' });
      setNote(`Backup created: ${data.driven.length} road pieces, ${data.drives.length} drives.`);
    } catch (e) {
      setNote(`Backup failed: ${(e as Error).message}`);
    } finally {
      setBackupBusy(false);
    }
  };

  const restoreBackup = async () => {
    if (backupBusy || tracking) return;
    setBackupBusy(true);
    try {
      const picked = await DocumentPicker.getDocumentAsync({ type: 'application/json', copyToCacheDirectory: true });
      if (picked.canceled || !picked.assets?.length) return;
      const text = await new File(picked.assets[0].uri).text();
      const result = await store.importBackup(JSON.parse(text));
      const data = await store.loadAll();
      for (const d of data.driven) {
        drivenRef.current.add(d.id);
        rememberDriven(d.id, drivenShapesRef.current.get(d.id) ?? d.shape, d.county);
      }
      for (const e of data.excluded) {
        excludedRef.current.add(e.id);
        excludedInfoRef.current.set(e.id, { c: e.county, l: e.lengthM });
      }
      unmarkedRef.current = await store.loadUnmarked();
      backfillFromSegments(Array.from(netRef.current.segs.values()));
      setDrivenIds(new Set(drivenRef.current));
      setExcludedIds(new Set(excludedRef.current));
      setUnmatchedCount(data.unmatched.length);
      setRawStats({ drives: data.driveCount, points: data.pointCount });
      if (data.homeCounty) setHomeCounty(data.homeCounty);
      setPanel(null);
      setNote(`Restored: ${result.driven} road pieces merged in, ${result.drivesAdded} new drives. Nothing on the phone was removed.`);
    } catch (e) {
      setNote(`Restore failed: ${(e as Error).message}`);
    } finally {
      setBackupBusy(false);
    }
  };

  // ---------- Stats ----------

  // Per-county and national figures. Totals come from county-stats.json;
  // driven km uses each driven road's stored shape and county. Excluded
  // roads come off both sides.
  const countyFigures = useMemo(() => {
    const n = countyStats?.counties.length ?? 0;
    const driven = new Array(n).fill(0);
    const excluded = new Array(n).fill(0);
    drivenIds.forEach((id) => {
      if (excludedIds.has(id)) return;
      const c = drivenCountyRef.current.get(id);
      if (c === undefined || c >= n) return;
      driven[c] += lengthRef.current.get(id) ?? 0;
    });
    excludedIds.forEach((id) => {
      const info = excludedInfoRef.current.get(id);
      if (info && info.c !== null && info.c < n && info.l !== null) excluded[info.c] += info.l;
    });
    const rows = (countyStats?.counties ?? []).map((name, i) => {
      const total = Math.max(0, countyStats!.totalMeters[i] - excluded[i]);
      return { code: i, name, driven: driven[i], total, percent: total > 0 ? (driven[i] / total) * 100 : 0 };
    });
    const nationalDriven = driven.reduce((a: number, b: number) => a + b, 0);
    const nationalTotal = Math.max(0, (countyStats?.nationalMeters ?? 0) - excluded.reduce((a: number, b: number) => a + b, 0));
    const unassigned = Array.from(drivenIds).filter((id) => !drivenCountyRef.current.has(id)).length;
    return { rows, nationalDriven, nationalTotal, nationalPercent: nationalTotal > 0 ? (nationalDriven / nationalTotal) * 100 : 0, unassigned };
  }, [countyStats, drivenIds, excludedIds]);

  const focusRow =
    currentCounty !== null ? countyFigures.rows[currentCounty] : countyFigures.rows.find((r) => r.name === homeCounty) ?? null;

  // ---------- Map drawing ----------

  // Image layer: set up once; falls back to lines if drawing isn't available.
  useEffect(() => {
    if (renderMode !== 'images' || rendererRef.current) return;
    try {
      rendererRef.current = new DrivenTileRenderer();
    } catch (e) {
      addLog(`image drawing unavailable: ${(e as Error).message}`);
      setNote('Map images unavailable on this phone — drawing roads as lines instead.');
      setRenderMode('lines');
    }
  }, [renderMode, addLog, setNote]);

  // Redraw the pictures when the driven roads change (not mid-drive or
  // while editing — those draw live lines instead).
  useEffect(() => {
    if (renderMode !== 'images' || tracking || editMode) return;
    const renderer = rendererRef.current;
    if (!renderer) return;
    const timer = setTimeout(async () => {
      const shapes = buildChains(
        Array.from(drivenIds).filter((id) => !excludedIds.has(id)),
        (id) => drivenShapesRef.current.get(id)
      ).map((c) => c.coords);
      renderer.setShapes(shapes);
      try {
        await renderer.renderRegion(visibleRegion, Dimensions.get('window').width);
      } catch (e) {
        addLog(`drawing failed: ${(e as Error).message}`);
      }
      setTileKey((k) => k + 1);
    }, 400);
    return () => clearTimeout(timer);
    // visibleRegion deliberately left out — handled by the effect below.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [drivenIds, excludedIds, tracking, editMode, renderMode]);

  // Draw any missing pictures for wherever the map is now.
  useEffect(() => {
    if (renderMode !== 'images') return;
    const renderer = rendererRef.current;
    if (!renderer || renderer.generation === 0) return;
    const timer = setTimeout(async () => {
      try {
        const written = await renderer.renderRegion(visibleRegion, Dimensions.get('window').width);
        if (written > 0) setTileKey((k) => k + 1);
      } catch (e) {
        addLog(`drawing failed: ${(e as Error).message}`);
      }
    }, 250);
    return () => clearTimeout(timer);
  }, [visibleRegion, renderMode, addLog]);

  const bounds = useMemo(() => {
    const padLat = visibleRegion.latitudeDelta * 0.6;
    const padLon = visibleRegion.longitudeDelta * 0.6;
    return {
      minLat: visibleRegion.latitude - padLat,
      maxLat: visibleRegion.latitude + padLat,
      minLon: visibleRegion.longitude - padLon,
      maxLon: visibleRegion.longitude + padLon,
    };
  }, [visibleRegion]);
  const inView = (c: Chain) => c.maxLat >= bounds.minLat && c.minLat <= bounds.maxLat && c.maxLon >= bounds.minLon && c.minLon <= bounds.maxLon;

  // Lines mode (fallback): driven roads joined into long lines.
  const drivenChains = useMemo(
    () =>
      renderMode === 'lines'
        ? buildChains(
            Array.from(drivenIds).filter((id) => !excludedIds.has(id)),
            (id) => drivenShapesRef.current.get(id)
          )
        : [],
    [drivenIds, excludedIds, renderMode]
  );
  const visibleChains = useMemo(() => drivenChains.filter(inView), [drivenChains, bounds]); // eslint-disable-line react-hooks/exhaustive-deps

  // Roads completed during the drive in progress, drawn live on top.
  const liveChains = useMemo(() => buildChains(liveIds, (id) => drivenShapesRef.current.get(id)), [liveIds]);

  const editZoomedIn = visibleRegion.latitudeDelta <= EDIT_MAX_LAT_DELTA;
  const visibleEditSegments = useMemo(() => {
    if (!editMode || !editZoomedIn) return [] as RoadSegment[];
    return netRef.current.inBox(bounds.minLat, bounds.minLon, bounds.maxLat, bounds.maxLon);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [editMode, editZoomedIn, bounds, netRev]);

  const drawLine = (key: string, coords: Coord[], color: string, z = 2) => [
    <Polyline key={`${key}-o`} coordinates={toLatLng(coords)} strokeColor="#0d3818" strokeWidth={7} lineCap="round" lineJoin="round" zIndex={z} />,
    <Polyline key={key} coordinates={toLatLng(coords)} strokeColor={color} strokeWidth={4} lineCap="round" lineJoin="round" zIndex={z + 1} />,
  ];

  // ---------- Onboarding ----------

  if (onboarded === null) {
    return (
      <View style={styles.onboardContainer}>
        <ActivityIndicator color="#39d353" size="large" />
      </View>
    );
  }

  if (onboarded === false) {
    return (
      <View style={styles.onboardContainer}>
        <Text style={styles.onboardTitle}>tarmacked</Text>
        {downloadingCounty ? (
          <>
            <Text style={styles.onboardText}>Downloading {downloadingCounty}…</Text>
            <ActivityIndicator color="#39d353" size="large" style={{ marginVertical: 16 }} />
            <Text style={styles.onboardText}>
              {downloadProgress.done} / {downloadProgress.total} tiles
            </Text>
          </>
        ) : (
          <>
            <Text style={styles.onboardText}>
              Pick your home county to download it now — everywhere else downloads automatically as you drive there.
            </Text>
            {onboardingError ? <Text style={styles.onboardError}>{onboardingError}</Text> : null}
            {onboardingCounties === null && !onboardingError && (
              <ActivityIndicator color="#39d353" size="large" style={{ marginVertical: 16 }} />
            )}
            <ScrollView style={styles.countyList}>
              {(onboardingCounties || []).map((c) => (
                <Pressable key={c} style={styles.countyRow} onPress={() => downloadHomeCounty(c)}>
                  <Text style={styles.countyRowText}>{c}</Text>
                </Pressable>
              ))}
            </ScrollView>
            <Pressable style={styles.skipLink} onPress={skipOnboarding}>
              <Text style={styles.linkText}>Skip for now</Text>
            </Pressable>
          </>
        )}
      </View>
    );
  }

  // ---------- Main screen ----------

  const elapsed = tracking ? Date.now() - driveStartRef.current : 0;
  const togglePanel = (p: Panel) => setPanel((cur) => (cur === p ? null : p));

  return (
    <View style={styles.container}>
      <MapView
        ref={mapRef}
        style={styles.map}
        provider={PROVIDER_DEFAULT}
        mapType={MAP_TYPES[mapTypeIndex]}
        initialRegion={region}
        showsUserLocation
        followsUserLocation={following && !editMode}
        onPanDrag={() => following && setFollowing(false)}
        onPress={onMapPress}
        onRegionChangeComplete={(r) => setVisibleRegion(r)}
      >
        {editMode &&
          visibleEditSegments.map((seg) => {
            const isExcluded = excludedIds.has(seg.id);
            const isDriven = drivenIds.has(seg.id);
            return (
              <Polyline
                key={seg.id}
                coordinates={toLatLng(seg.coords)}
                strokeColor={isExcluded ? '#a03030' : isDriven ? '#39d353' : '#555'}
                strokeWidth={isExcluded || isDriven ? 5 : 3}
                lineCap="round"
                lineJoin="round"
                lineDashPattern={isExcluded ? [6, 4] : undefined}
                tappable
                onPress={() => handleEditTap(seg.id)}
              />
            );
          })}

        {!editMode && renderMode === 'images' && rendererRef.current && rendererRef.current.generation > 0 && (
          <LocalTile key={`tiles-${tileKey}`} pathTemplate={rendererRef.current.pathTemplate} tileSize={256} zIndex={1} />
        )}

        {!editMode && renderMode === 'lines' && visibleChains.flatMap((c, i) => drawLine(`d${i}`, c.coords, '#39d353'))}

        {tracking && liveChains.flatMap((c, i) => drawLine(`live${i}`, c.coords, '#39d353', 4))}

        {tracking && liveTrail.length > 1 && (
          <Polyline
            coordinates={liveTrail.map((p) => ({ latitude: p.latitude, longitude: p.longitude }))}
            strokeColor="#3a8dff"
            strokeWidth={3}
            lineCap="round"
            lineJoin="round"
            zIndex={6}
          />
        )}

        {selectedDrive && selectedDrive.points.length > 1 && (
          <Polyline
            coordinates={selectedDrive.points.map((p) => ({ latitude: p.latitude, longitude: p.longitude }))}
            strokeColor="#ff9f1a"
            strokeWidth={4}
            lineCap="round"
            lineJoin="round"
            zIndex={7}
          />
        )}

        {rawSessions &&
          rawSessions.map((session, i) =>
            session.length > 1 ? (
              <Polyline
                key={`raw-${i}`}
                coordinates={session.map((p) => ({ latitude: p.latitude, longitude: p.longitude }))}
                strokeColor="#3a8dff"
                strokeWidth={2}
                zIndex={8}
              />
            ) : null
          )}
      </MapView>

      {/* Top bar */}
      <View style={styles.topBar}>
        <View style={styles.topGroup}>
          <Pressable style={[styles.chip, panel === 'stats' && styles.chipActive]} onPress={() => togglePanel('stats')}>
            <Text style={styles.chipText}>Stats</Text>
          </Pressable>
          <Pressable style={[styles.chip, panel === 'drives' && styles.chipActive]} onPress={openDrives}>
            <Text style={styles.chipText}>Drives</Text>
          </Pressable>
          <Pressable style={[styles.chip, panel === 'dev' && styles.chipActive]} onPress={() => togglePanel('dev')}>
            <Text style={styles.chipText}>⚙</Text>
          </Pressable>
        </View>
        <Pressable style={styles.chip} onPress={() => setMapTypeIndex((i) => (i + 1) % MAP_TYPES.length)}>
          <Text style={[styles.chipText, { textTransform: 'capitalize' }]}>{MAP_TYPES[mapTypeIndex]}</Text>
        </Pressable>
      </View>

      {/* Messages */}
      {recheckProgress !== null ? (
        <View style={styles.toast}>
          <Text style={styles.toastText}>Re-checking your drives… {Math.round(recheckProgress * 100)}%</Text>
        </View>
      ) : note ? (
        <Pressable style={styles.toast} onPress={() => setNote('')}>
          <Text style={styles.toastText}>{note}</Text>
        </Pressable>
      ) : null}

      {/* Stats */}
      {panel === 'stats' && (
        <View style={styles.panel}>
          <ScrollView>
            <Text style={styles.panelTitle}>Stats</Text>
            {countyStats ? (
              <>
                <Text style={styles.statsHeadline}>
                  Ireland {countyFigures.nationalPercent.toFixed(3)}% · {km(countyFigures.nationalDriven)} /{' '}
                  {km(countyFigures.nationalTotal, 0)} km
                </Text>
                {countyFigures.rows.map((r) => (
                  <View key={r.name} style={[styles.countyStatRow, r.code === focusRow?.code && styles.countyStatRowCurrent]}>
                    <Text style={[styles.countyStatName, r.driven > 0 && styles.countyStatNameDriven]}>{shortCounty(r.name)}</Text>
                    <Text style={styles.countyStatValue}>
                      {r.percent.toFixed(2)}% · {km(r.driven)} / {km(r.total, 0)} km
                    </Text>
                  </View>
                ))}
                {countyFigures.unassigned > 0 && (
                  <Text style={styles.small}>
                    {countyFigures.unassigned} road pieces aren't counted yet — their county fills in once the road data for
                    that area downloads.
                  </Text>
                )}
              </>
            ) : (
              <Text style={styles.small}>Road totals haven't loaded yet — connect to the internet once and they're saved for offline use.</Text>
            )}
            <Text style={[styles.panelTitle, { marginTop: 16 }]}>Your data</Text>
            <Text style={styles.small}>
              Saved on this phone. Back up to keep a copy somewhere safe (Files, iCloud Drive, email). Restoring merges a backup in
              — it never removes anything already on the phone.
            </Text>
            <View style={styles.row}>
              <Pressable style={[styles.button, styles.buttonBlue]} onPress={exportBackup} disabled={backupBusy}>
                <Text style={styles.buttonText}>{backupBusy ? 'Working…' : 'Back up'}</Text>
              </Pressable>
              <Pressable style={[styles.button, styles.buttonGrey]} onPress={restoreBackup} disabled={backupBusy || tracking}>
                <Text style={styles.buttonText}>Restore</Text>
              </Pressable>
            </View>
          </ScrollView>
        </View>
      )}

      {/* Drives */}
      {panel === 'drives' && (
        <View style={styles.panel}>
          <Text style={styles.panelTitle}>Drives</Text>
          {drives === null ? (
            <ActivityIndicator color="#39d353" />
          ) : drives.length === 0 ? (
            <Text style={styles.small}>No drives yet — tap Start when you set off.</Text>
          ) : (
            <ScrollView>
              {drives.map((d) => {
                const selected = selectedDrive?.id === d.id;
                return (
                  <Pressable key={d.id} style={[styles.driveRow, selected && styles.driveRowSelected]} onPress={() => showDrive(d.id)}>
                    <View style={{ flex: 1 }}>
                      <Text style={styles.driveWhen}>{formatWhen(d.startedAt)}</Text>
                      <Text style={styles.driveInfo}>
                        {d.endedAt ? `${formatDuration(d.endedAt - d.startedAt)} · ` : ''}
                        {d.distanceM !== null ? `${km(d.distanceM)} km` : `${d.pointCount} points`}
                        {d.newM !== null && d.newM > 0 ? ` · +${km(d.newM)} km new` : ''}
                      </Text>
                    </View>
                    {selected && (
                      <Pressable
                        style={[styles.smallButton, deleteConfirmId === d.id && styles.smallButtonDanger]}
                        onPress={() => deleteDrive(d.id)}
                      >
                        <Text style={styles.chipText}>{deleteConfirmId === d.id ? 'Tap to confirm' : 'Delete'}</Text>
                      </Pressable>
                    )}
                  </Pressable>
                );
              })}
            </ScrollView>
          )}
          {selectedDrive && <Text style={styles.small}>Shown in orange on the map. Tap it again to hide.</Text>}
        </View>
      )}

      {/* Dev tools */}
      {panel === 'dev' && (
        <View style={styles.panel}>
          <ScrollView>
            <Text style={styles.panelTitle}>Developer tools</Text>
            <View style={styles.row}>
              <Pressable
                style={[styles.button, styles.buttonBlue]}
                disabled={tracking}
                onPress={() => {
                  setFollowing(false);
                  setEditMode(true);
                  setPanel(null);
                }}
              >
                <Text style={styles.buttonText}>Edit roads</Text>
              </Pressable>
              <Pressable
                style={[styles.button, styles.buttonPurple]}
                disabled={tracking || recheckProgress !== null}
                onPress={() => {
                  setPanel(null);
                  runRecheck('manual');
                }}
              >
                <Text style={styles.buttonText}>Re-check all drives</Text>
              </Pressable>
            </View>
            {removedCount > 0 && (
              <Pressable style={[styles.button, styles.buttonGrey]} onPress={undoRecheck} disabled={tracking}>
                <Text style={styles.buttonText}>Put back {removedCount} road pieces removed by re-checks</Text>
              </Pressable>
            )}
            <View style={styles.row}>
              <Pressable style={[styles.button, styles.buttonGrey, rawSessions && styles.buttonOn]} onPress={toggleRawTrail}>
                <Text style={styles.buttonText}>{rawSessions ? 'Hide' : 'Show'} raw GPS</Text>
              </Pressable>
              <Pressable style={[styles.button, styles.buttonGrey]} onPress={toggleRenderMode}>
                <Text style={styles.buttonText}>Draw as: {renderMode}</Text>
              </Pressable>
            </View>
            <View style={styles.row}>
              <Pressable style={[styles.button, styles.buttonGrey, simulateTaps && styles.buttonOn]} onPress={() => setSimulateTaps((v) => !v)}>
                <Text style={styles.buttonText}>Tap-to-simulate: {simulateTaps ? 'on' : 'off'}</Text>
              </Pressable>
              <Pressable style={[styles.button, styles.buttonGrey]} onPress={refreshRoadData} disabled={tracking || refreshing}>
                <Text style={styles.buttonText}>{refreshing ? 'Refreshing…' : 'Refresh road data'}</Text>
              </Pressable>
            </View>
            <View style={styles.row}>
              <Pressable
                style={[styles.button, styles.buttonRed, confirming === 'uninstall' && styles.buttonRedConfirm]}
                onPress={() => confirmThen('uninstall', uninstallAreas)}
                disabled={tracking}
              >
                <Text style={styles.buttonText}>{confirming === 'uninstall' ? 'Tap again' : 'Clear road data'}</Text>
              </Pressable>
              <Pressable
                style={[styles.button, styles.buttonRed, confirming === 'reset' && styles.buttonRedConfirm]}
                onPress={() => confirmThen('reset', resetMap)}
                disabled={tracking}
              >
                <Text style={styles.buttonText}>{confirming === 'reset' ? 'Tap again to wipe' : 'Reset map'}</Text>
              </Pressable>
            </View>
            <Text style={styles.small}>
              Home county: {homeCounty || 'none'} · road pieces loaded: {netRef.current.size} · areas: {knownTilesRef.current.size}
              {'\n'}Driven: {drivenIds.size} · excluded: {excludedIds.size} · off-road GPS points: {unmatchedCount}
              {'\n'}Saved drives: {rawStats.drives} ({rawStats.points} points)
            </Text>
            <Text style={[styles.panelTitle, { marginTop: 12 }]}>Log</Text>
            <Text style={styles.logText}>{log.length ? log.join('\n') : '—'}</Text>
          </ScrollView>
        </View>
      )}

      {!following && !editMode && (
        <Pressable style={styles.recentreButton} onPress={recentre}>
          <Text style={styles.recentreText}>◎</Text>
        </Pressable>
      )}

      {/* Bottom bar */}
      {editMode ? (
        <View style={styles.bottomBar}>
          <View style={{ flex: 1 }}>
            <Text style={styles.barLine}>
              {!editZoomedIn
                ? 'Zoom in to edit roads'
                : editAction === 'exclude'
                  ? 'Tap a road: private / gone'
                  : 'Tap a green road to un-mark it'}
            </Text>
            <View style={[styles.row, { justifyContent: 'flex-start', marginTop: 6 }]}>
              <Pressable style={[styles.smallButton, editAction === 'exclude' && styles.chipActive]} onPress={() => setEditAction('exclude')}>
                <Text style={styles.chipText}>Private / gone</Text>
              </Pressable>
              <Pressable style={[styles.smallButton, editAction === 'undrive' && styles.chipActive]} onPress={() => setEditAction('undrive')}>
                <Text style={styles.chipText}>Un-mark</Text>
              </Pressable>
            </View>
          </View>
          <Pressable style={[styles.mainButton, styles.buttonBlue]} onPress={() => setEditMode(false)}>
            <Text style={styles.buttonText}>Done</Text>
          </Pressable>
        </View>
      ) : (
        <View style={styles.bottomBar}>
          <View style={{ flex: 1 }}>
            {countyStats ? (
              <>
                <Text style={styles.barLine}>
                  {focusRow ? `${shortCounty(focusRow.name)} ${focusRow.percent.toFixed(2)}%` : 'Ireland'}
                  <Text style={styles.barDim}>{`  ·  Ireland ${countyFigures.nationalPercent.toFixed(3)}%`}</Text>
                </Text>
              </>
            ) : (
              <Text style={styles.barDim}>Connect once to load road totals</Text>
            )}
            {tracking && (
              <Text style={styles.barLive}>
                ● {formatDuration(elapsed)} · {km(driveDistanceRef.current)} km · +{km(driveNewMRef.current)} km new
              </Text>
            )}
          </View>
          <Pressable
            style={[styles.mainButton, tracking && styles.mainButtonStop, !tracking && recheckProgress !== null && styles.mainButtonBusy]}
            onPress={tracking ? stop : start}
            disabled={!tracking && recheckProgress !== null}
          >
            <Text style={styles.buttonText}>{tracking ? 'Stop' : 'Start'}</Text>
          </Pressable>
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#111' },
  map: { flex: 1 },
  onboardContainer: { flex: 1, backgroundColor: '#111', alignItems: 'center', justifyContent: 'center', padding: 24 },
  onboardTitle: { color: '#fff', fontSize: 32, fontWeight: '700', marginBottom: 20 },
  onboardText: { color: '#aaa', fontSize: 14, textAlign: 'center', marginBottom: 12 },
  onboardError: { color: '#e0a030', fontSize: 13, textAlign: 'center', marginBottom: 12 },
  countyList: { maxHeight: 320, alignSelf: 'stretch', marginTop: 8 },
  countyRow: { paddingVertical: 12, paddingHorizontal: 16, backgroundColor: '#1c1c1c', borderRadius: 8, marginBottom: 6 },
  countyRowText: { color: '#fff', fontSize: 15, textAlign: 'center' },
  skipLink: { marginTop: 16 },
  linkText: { color: '#6aa9ff', fontSize: 14 },

  topBar: { position: 'absolute', top: 56, left: 12, right: 12, flexDirection: 'row', justifyContent: 'space-between' },
  topGroup: { flexDirection: 'row', gap: 8 },
  chip: { backgroundColor: 'rgba(17,17,17,0.88)', borderRadius: 18, paddingVertical: 8, paddingHorizontal: 14 },
  chipActive: { backgroundColor: '#2f6f3a' },
  chipText: { color: '#fff', fontSize: 13, fontWeight: '600' },

  toast: {
    position: 'absolute',
    bottom: 116,
    left: 12,
    right: 72,
    backgroundColor: 'rgba(17,17,17,0.92)',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  toastText: { color: '#e8c070', fontSize: 13 },

  panel: {
    position: 'absolute',
    top: 104,
    left: 12,
    right: 12,
    maxHeight: '58%',
    backgroundColor: 'rgba(17,17,17,0.96)',
    borderRadius: 14,
    padding: 16,
  },
  panelTitle: { color: '#fff', fontSize: 16, fontWeight: '700', marginBottom: 10 },
  small: { color: '#8a8a8a', fontSize: 12, marginTop: 8, lineHeight: 17 },
  statsHeadline: { color: '#39d353', fontSize: 14, fontWeight: '600', marginBottom: 8 },
  countyStatRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 5, paddingHorizontal: 6, borderRadius: 6 },
  countyStatRowCurrent: { backgroundColor: 'rgba(57,211,83,0.15)' },
  countyStatName: { color: '#888', fontSize: 13 },
  countyStatNameDriven: { color: '#fff', fontWeight: '600' },
  countyStatValue: { color: '#aaa', fontSize: 12 },
  driveRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 9, paddingHorizontal: 8, borderRadius: 8 },
  driveRowSelected: { backgroundColor: 'rgba(255,159,26,0.15)' },
  driveWhen: { color: '#fff', fontSize: 14, fontWeight: '600' },
  driveInfo: { color: '#9a9a9a', fontSize: 12, marginTop: 2 },
  logText: { color: '#7fd67f', fontSize: 10, fontFamily: 'Courier' },

  row: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginTop: 8 },
  button: { flexGrow: 1, paddingVertical: 11, paddingHorizontal: 14, borderRadius: 10, alignItems: 'center' },
  buttonText: { color: '#fff', fontSize: 14, fontWeight: '600', textAlign: 'center' },
  buttonBlue: { backgroundColor: '#2a4f8a' },
  buttonPurple: { backgroundColor: '#5a3a8a' },
  buttonGrey: { backgroundColor: '#333' },
  buttonOn: { backgroundColor: '#3a6fb0' },
  buttonRed: { backgroundColor: '#5a2a2a' },
  buttonRedConfirm: { backgroundColor: '#a03030' },
  smallButton: { backgroundColor: '#333', borderRadius: 8, paddingVertical: 7, paddingHorizontal: 12 },
  smallButtonDanger: { backgroundColor: '#a03030' },

  recentreButton: {
    position: 'absolute',
    bottom: 124,
    right: 16,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(17,17,17,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recentreText: { color: '#6aa9ff', fontSize: 24, fontWeight: '700' },

  bottomBar: {
    position: 'absolute',
    bottom: 34,
    left: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(17,17,17,0.9)',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  barLine: { color: '#fff', fontSize: 15, fontWeight: '600' },
  barDim: { color: '#9a9a9a', fontSize: 13, fontWeight: '400' },
  barLive: { color: '#ff7a7a', fontSize: 13, marginTop: 4 },
  mainButton: { backgroundColor: '#2a6f2a', paddingVertical: 14, paddingHorizontal: 26, borderRadius: 12 },
  mainButtonStop: { backgroundColor: '#8a2a2a' },
  mainButtonBusy: { opacity: 0.4 },
});
